# -*- coding: utf-8 -*-
"""video_morphed_net

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cPufLAMMavQp4IJQUZ_kG8MMvnKSL5H6
"""

# ==================== CORRECTED IMPORTS ====================
import os
import sys
import random
import time
import json
import gc
from pathlib import Path
from collections import defaultdict
from datetime import datetime

import numpy as np
import cv2
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import torchvision
from torchvision import models, transforms
import matplotlib.pyplot as plt
from sklearn.model_selection import StratifiedKFold, train_test_split
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score, accuracy_score, precision_recall_fscore_support
from tqdm import tqdm
import warnings
warnings.filterwarnings('ignore')

import os
import random
import zipfile
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
import cv2
from pathlib import Path
from torch.utils.data import Dataset, DataLoader
from sklearn.model_selection import train_test_split
import torchvision.models as models

# Seed
def set_seed(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

set_seed(42)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

from google.colab import drive

drive.mount('/content/drive', force_remount=True)

zip_path = "/content/drive/MyDrive/Faceforensics_dataset/archive.zip"
extract_path = "/content/ffpp_data"

if not os.path.exists(extract_path):
    print("Extracting dataset...")
    with zipfile.ZipFile(zip_path, 'r') as zip_ref:
        zip_ref.extractall(extract_path)
    print("Extraction complete!")

dataset_path = extract_path
print("Dataset ready at:", dataset_path)

!ls /content/ffpp_data

DATASET_PATH = "/content/ffpp_data/FF++"

!ls /content/ffpp_data/FF++

import os

for root, dirs, files in os.walk(dataset_path):
    print("ROOT:", root)
    print("DIRS:", dirs)
    print("FILES:", files[:5])
    print("-"*50)
    break

def load_dataset(data_path):
    video_paths = []
    labels = []

    real_root = Path(data_path) / "original_sequences"
    fake_root = Path(data_path) / "manipulated_sequences"

    for video in real_root.rglob("*.mp4"):
        video_paths.append(str(video))
        labels.append(0)

    for video in fake_root.rglob("*.mp4"):
        video_paths.append(str(video))
        labels.append(1)

    print("Total videos:", len(video_paths))
    print("Real:", labels.count(0))
    print("Fake:", labels.count(1))

    return video_paths, labels

video_paths, labels = load_dataset(dataset_path)

# ==================== ENHANCED 15-STEP VIDEO PREPROCESSOR ====================
class EnhancedVideoPreprocessor:
    def __init__(self, config):
        self.config = config
        self.face_detector = self._initialize_face_detectors()
        self.face_landmark_detector = self._initialize_landmark_detector()
        self.transforms = self._get_transforms()

        # Check for face alignment (optional)
        try:
            import face_alignment
            self.fa = face_alignment.FaceAlignment(
                face_alignment.LandmarksType.TWO_D,
                device='cuda' if torch.cuda.is_available() else 'cpu',
                flip_input=False
            )
        except ImportError:
            self.fa = None
            print("Warning: Face alignment not available, skipping alignment step")

        # Initialize OpenCV cascade as fallback
        self.face_cascade = cv2.CascadeClassifier(
            cv2.data.haarcascades + 'haarcascade_frontalface_default.xml'
        )

    def _initialize_face_detectors(self):
        """Initialize multiple face detectors for robustness"""
        detectors = {}

        # Check for MediaPipe
        try:
            import mediapipe as mp
            mp_face_detection = mp.solutions.face_detection
            detectors['mediapipe'] = mp_face_detection.FaceDetection(
                model_selection=1,
                min_detection_confidence=0.7
            )
        except ImportError:
            detectors['mediapipe'] = None

        # Check for MTCNN
        try:
            from facenet_pytorch import MTCNN
            detectors['mtcnn'] = MTCNN(
                keep_all=True,
                device=device,
                min_face_size=50
            )
        except ImportError:
            detectors['mtcnn'] = None

        # Dlib detector (you already have this)
        try:
            detectors['dlib'] = dlib.get_frontal_face_detector()
        except:
            detectors['dlib'] = None

        return detectors

    def _initialize_landmark_detector(self):
        """Initialize facial landmark detector"""
        predictor_path = '/content/shape_predictor_68_face_landmarks.dat'

        # Download if not exists (only in Colab)
        if IN_COLAB and not os.path.exists(predictor_path):
            try:
                print("Downloading facial landmark predictor...")
                # Use os.system instead of ! for better compatibility
                os.system('wget -q http://dlib.net/files/shape_predictor_68_face_landmarks.dat.bz2')
                os.system('bzip2 -d shape_predictor_68_face_landmarks.dat.bz2')
                print("Download complete!")
            except:
                print("Could not download landmark predictor")
                return None

        try:
            if os.path.exists(predictor_path):
                return dlib.shape_predictor(predictor_path)
        except:
            print("Could not initialize landmark predictor")

        return None

    def _get_transforms(self):
        """Advanced augmentation pipeline"""
        return A.Compose([
            A.HorizontalFlip(p=0.5),
            A.Rotate(limit=15, p=0.3),
            A.RandomBrightnessContrast(brightness_limit=0.2, contrast_limit=0.2, p=0.5),
            A.GaussianBlur(blur_limit=(3, 7), p=0.2),
            A.CLAHE(clip_limit=2.0, tile_grid_size=(8, 8), p=0.3),
            A.Normalize(
                mean=[0.485, 0.456, 0.406],
                std=[0.229, 0.224, 0.225],
                max_pixel_value=255.0
            ),
            ToTensorV2()
        ])

    def step1_frame_extraction(self, video_path):
        """Step 1: Extract frames from video"""
        cap = cv2.VideoCapture(video_path)
        frames = []

        if not cap.isOpened():
            print(f"Cannot open video: {video_path}")
            return None

        frame_count = 0
        while len(frames) < self.config.FRAMES_PER_VIDEO:
            ret, frame = cap.read()
            if not ret:
                break

            if frame_count % self.config.SAMPLE_RATE == 0:
                frames.append(frame)

            frame_count += 1

        cap.release()

        if len(frames) == 0:
            return None

        return frames

    def step2_face_detection_ensemble(self, frame):
        """Step 2: Ensemble face detection"""
        rgb_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        detections = []

        # MediaPipe
        if self.face_detector['mediapipe']:
            try:
                results = self.face_detector['mediapipe'].process(rgb_frame)
                if results.detections:
                    detection = results.detections[0]
                    bbox = detection.location_data.relative_bounding_box
                    h, w, _ = frame.shape

                    x = int(bbox.xmin * w)
                    y = int(bbox.ymin * h)
                    width = int(bbox.width * w)
                    height = int(bbox.height * h)

                    if width > 20 and height > 20:
                        detections.append((x, y, width, height))
            except:
                pass

        # MTCNN
        if self.face_detector['mtcnn']:
            try:
                boxes, _ = self.face_detector['mtcnn'].detect(rgb_frame)
                if boxes is not None and len(boxes) > 0:
                    box = boxes[0]
                    x, y, x2, y2 = box
                    w, h = x2 - x, y2 - y
                    if w > 20 and h > 20:
                        detections.append((int(x), int(y), int(w), int(h)))
            except:
                pass

        # Dlib
        if self.face_detector['dlib']:
            try:
                gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
                dlib_results = self.face_detector['dlib'](gray, 1)
                if len(dlib_results) > 0:
                    rect = dlib_results[0]
                    x, y, w, h = rect.left(), rect.top(), rect.width(), rect.height()
                    if w > 20 and h > 20:
                        detections.append((x, y, w, h))
            except:
                pass

        # OpenCV Cascade as fallback
        if not detections:
            try:
                gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
                faces = self.face_cascade.detectMultiScale(gray, 1.1, 4)
                if len(faces) > 0:
                    x, y, w, h = faces[0]
                    detections.append((x, y, w, h))
            except:
                pass

        if detections:
            # Return the largest detection
            return max(detections, key=lambda d: d[2] * d[3])

        return None

    def step3_face_alignment(self, face_image):
        """Step 3: Face alignment using landmarks"""
        if self.fa is None or face_image is None:
            return face_image

        try:
            landmarks = self.fa.get_landmarks(face_image)
            if landmarks is not None and len(landmarks) > 0:
                landmarks = landmarks[0]

                # Get eye centers
                left_eye = landmarks[36:42].mean(axis=0)
                right_eye = landmarks[42:48].mean(axis=0)

                # Calculate angle
                dy = right_eye[1] - left_eye[1]
                dx = right_eye[0] - left_eye[0]
                angle = np.degrees(np.arctan2(dy, dx))

                # Rotate face
                center = (face_image.shape[1] // 2, face_image.shape[0] // 2)
                rotation_matrix = cv2.getRotationMatrix2D(center, angle, 1.0)
                aligned = cv2.warpAffine(face_image, rotation_matrix,
                                        (face_image.shape[1], face_image.shape[0]),
                                        flags=cv2.INTER_CUBIC)
                return aligned
        except:
            pass

        return face_image

    def step4_illumination_normalization(self, face_image):
        """Step 4: Advanced illumination normalization"""
        if face_image is None:
            return None

        try:
            # Convert to LAB color space
            lab = cv2.cvtColor(face_image, cv2.COLOR_BGR2LAB)
            l, a, b = cv2.split(lab)

            # Apply CLAHE to L channel
            clahe = cv2.createCLAHE(
                clipLimit=self.config.CLAHE_CLIP_LIMIT,
                tileGridSize=(self.config.CLAHE_TILE_SIZE, self.config.CLAHE_TILE_SIZE)
            )
            l_eq = clahe.apply(l)

            # Merge and convert back
            lab_eq = cv2.merge([l_eq, a, b])
            normalized = cv2.cvtColor(lab_eq, cv2.COLOR_LAB2BGR)

            return normalized
        except:
            return face_image

    def step5_color_normalization(self, face_image):
        """Step 5: Color normalization"""
        if face_image is None:
            return None

        try:
            # Convert to float32
            face_float = face_image.astype(np.float32) / 255.0

            # Calculate mean and std
            mean = np.array([0.485, 0.456, 0.406])
            std = np.array([0.229, 0.224, 0.225])

            # Normalize
            normalized = (face_float - mean) / std

            # Convert back to uint8
            normalized = ((normalized - normalized.min()) /
                         (normalized.max() - normalized.min()) * 255).astype(np.uint8)

            return normalized
        except:
            return face_image

    def step6_histogram_equalization(self, face_image):
        """Step 6: Adaptive histogram equalization"""
        if face_image is None:
            return None

        try:
            # Convert to YCrCb
            ycrcb = cv2.cvtColor(face_image, cv2.COLOR_BGR2YCrCb)
            y, cr, cb = cv2.split(ycrcb)

            # Apply CLAHE to Y channel
            clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8, 8))
            y_eq = clahe.apply(y)

            # Merge back
            ycrcb_eq = cv2.merge([y_eq, cr, cb])
            enhanced = cv2.cvtColor(ycrcb_eq, cv2.COLOR_YCrCb2BGR)

            return enhanced
        except:
            return face_image

    def step7_sharpening(self, face_image):
        """Step 7: Edge-preserving sharpening"""
        if face_image is None:
            return None

        try:
            # Unsharp masking
            blurred = cv2.GaussianBlur(face_image, (0, 0), 3)
            sharpened = cv2.addWeighted(face_image, 1.5, blurred, -0.5, 0)

            return sharpened
        except:
            return face_image

    def step8_noise_reduction(self, face_image):
        """Step 8: Noise reduction"""
        if face_image is None:
            return None

        try:
            # Bilateral filtering
            denoised = cv2.bilateralFilter(face_image, 9, 75, 75)

            return denoised
        except:
            return face_image

    def step9_texture_enhancement(self, face_image):
        """Step 9: Texture enhancement"""
        if face_image is None:
            return None

        try:
            gray = cv2.cvtColor(face_image, cv2.COLOR_BGR2GRAY)

            # Calculate gradients
            sobelx = cv2.Sobel(gray, cv2.CV_64F, 1, 0, ksize=3)
            sobely = cv2.Sobel(gray, cv2.CV_64F, 0, 1, ksize=3)
            magnitude = np.sqrt(sobelx**2 + sobely**2)

            # Normalize
            magnitude = np.uint8(255 * magnitude / np.max(magnitude))

            # Convert back to BGR and blend
            texture_enhanced = cv2.cvtColor(magnitude, cv2.COLOR_GRAY2BGR)
            enhanced = cv2.addWeighted(face_image, 0.7, texture_enhanced, 0.3, 0)

            return enhanced
        except:
            return face_image

    def step10_quality_assessment(self, face_image):
        """Step 10: Quality assessment"""
        if face_image is None:
            return None

        try:
            gray = cv2.cvtColor(face_image, cv2.COLOR_BGR2GRAY)

            # Calculate Laplacian variance (sharpness)
            laplacian = cv2.Laplacian(gray, cv2.CV_64F)
            sharpness = laplacian.var()

            # Calculate contrast
            contrast = gray.std()

            # Enhance if quality is low
            if sharpness < 100:
                face_image = self.step7_sharpening(face_image)

            return face_image
        except:
            return face_image

    def step11_skin_detection(self, face_image):
        """Step 11: Skin region enhancement"""
        if face_image is None:
            return None

        try:
            # Convert to HSV
            hsv = cv2.cvtColor(face_image, cv2.COLOR_BGR2HSV)

            # Define skin color range
            lower_skin = np.array([0, 20, 70], dtype=np.uint8)
            upper_skin = np.array([20, 255, 255], dtype=np.uint8)

            # Create skin mask
            mask = cv2.inRange(hsv, lower_skin, upper_skin)
            mask = cv2.medianBlur(mask, 5)

            # Apply mask
            skin_only = cv2.bitwise_and(face_image, face_image, mask=mask)

            return skin_only
        except:
            return face_image

    def step12_gamma_correction(self, face_image):
        """Step 12: Gamma correction"""
        if face_image is None:
            return None

        try:
            # Build a lookup table mapping pixel values [0, 255] to adjusted values
            gamma = 1.2
            inv_gamma = 1.0 / gamma
            table = np.array([((i / 255.0) ** inv_gamma) * 255
                            for i in np.arange(0, 256)]).astype("uint8")

            # Apply gamma correction
            corrected = cv2.LUT(face_image, table)

            return corrected
        except:
            return face_image

    def step13_background_subtraction(self, face_image):
        """Step 13: Background subtraction/attention"""
        if face_image is None:
            return None

        try:
            # Create attention mask focusing on central region
            h, w = face_image.shape[:2]
            mask = np.zeros((h, w), dtype=np.uint8)
            center_x, center_y = w // 2, h // 2
            radius = min(w, h) // 2

            # Create circular mask
            cv2.circle(mask, (center_x, center_y), radius, 255, -1)

            # Apply Gaussian blur to mask edges
            mask = cv2.GaussianBlur(mask, (21, 21), 0)
            mask = mask / 255.0

            # Apply mask to each channel
            result = face_image.copy()
            for i in range(3):
                result[:, :, i] = result[:, :, i] * mask

            return result
        except:
            return face_image

    def step14_temporal_consistency(self, frames):
        """Step 14: Temporal consistency check"""
        if len(frames) < 2:
            return frames

        # Calculate optical flow between consecutive frames
        consistent_frames = [frames[0]]

        for i in range(1, len(frames)):
            prev_gray = cv2.cvtColor(frames[i-1], cv2.COLOR_BGR2GRAY)
            curr_gray = cv2.cvtColor(frames[i], cv2.COLOR_BGR2GRAY)

            # Calculate optical flow
            flow = cv2.calcOpticalFlowFarneback(prev_gray, curr_gray,
                                               None, 0.5, 3, 15, 3, 5, 1.2, 0)

            # Calculate magnitude of flow
            mag, _ = cv2.cartToPolar(flow[..., 0], flow[..., 1])
            avg_mag = np.mean(mag)

            # If motion is too high, use weighted average
            if avg_mag > 5.0:
                blended = cv2.addWeighted(frames[i-1], 0.7, frames[i], 0.3, 0)
                consistent_frames.append(blended)
            else:
                consistent_frames.append(frames[i])

        return consistent_frames

    def step15_final_normalization(self, face_image):
        """Step 15: Final normalization for model input"""
        if face_image is None:
            return None

        try:
            # Resize to target size
            resized = cv2.resize(face_image, self.config.FRAME_SIZE,
                                interpolation=cv2.INTER_CUBIC)

            # Convert to RGB
            rgb = cv2.cvtColor(resized, cv2.COLOR_BGR2RGB)

            return rgb
        except:
            return None

    def preprocess_video(self, video_path, is_training=True):
        """Complete 15-step preprocessing pipeline"""
        # Step 1: Extract frames
        frames = self.step1_frame_extraction(video_path)
        if frames is None:
            # Return dummy frames
            dummy_frames = torch.zeros(self.config.FRAMES_PER_VIDEO, 3,
                                      *self.config.FRAME_SIZE)
            return dummy_frames

        processed_frames = []

        for frame in frames[:self.config.FRAMES_PER_VIDEO]:
            # Step 2: Face detection
            bbox = self.step2_face_detection_ensemble(frame)

            if bbox:
                x, y, w, h = bbox

                # Expand bounding box
                x = max(0, x - int(w * 0.1))
                y = max(0, y - int(h * 0.1))
                w = min(frame.shape[1] - x, int(w * 1.2))
                h = min(frame.shape[0] - y, int(h * 1.2))

                # Extract face
                face = frame[y:y+h, x:x+w]

                if face.size == 0:
                    continue

                # Apply preprocessing steps
                face = self.step3_face_alignment(face)
                face = self.step4_illumination_normalization(face)
                face = self.step5_color_normalization(face)
                face = self.step6_histogram_equalization(face)
                face = self.step7_sharpening(face)
                face = self.step8_noise_reduction(face)
                face = self.step9_texture_enhancement(face)
                face = self.step10_quality_assessment(face)
                face = self.step11_skin_detection(face)
                face = self.step12_gamma_correction(face)
                face = self.step13_background_subtraction(face)

                # Step 15: Final normalization
                face_rgb = self.step15_final_normalization(face)

                if face_rgb is not None:
                    if is_training:
                        # Apply augmentations
                        augmented = self.transforms(image=face_rgb)['image']
                        processed_frames.append(augmented)
                    else:
                        # Normalize for inference
                        face_tensor = face_rgb.astype(np.float32) / 255.0
                        mean = np.array([0.485, 0.456, 0.406])
                        std = np.array([0.229, 0.224, 0.225])
                        face_tensor = (face_tensor - mean) / std
                        face_tensor = torch.from_numpy(face_tensor).permute(2, 0, 1)
                        processed_frames.append(face_tensor)

        # Step 14: Temporal consistency (if enough frames)
        if len(processed_frames) > 1:
            # Convert back to numpy for consistency check
            numpy_frames = []
            for frame in processed_frames:
                if isinstance(frame, torch.Tensor):
                    numpy_frames.append(frame.permute(1, 2, 0).numpy() * 255)
                else:
                    numpy_frames.append(frame)

            consistent_frames = self.step14_temporal_consistency(numpy_frames)

            # Convert back to tensors
            processed_frames = []
            for frame in consistent_frames:
                if is_training:
                    augmented = self.transforms(image=frame.astype(np.uint8))['image']
                    processed_frames.append(augmented)
                else:
                    frame = frame.astype(np.float32) / 255.0
                    mean = np.array([0.485, 0.456, 0.406])
                    std = np.array([0.229, 0.224, 0.225])
                    frame = (frame - mean) / std
                    frame = torch.from_numpy(frame).permute(2, 0, 1)
                    processed_frames.append(frame)

        # Pad if not enough frames
        while len(processed_frames) < self.config.FRAMES_PER_VIDEO:
            if is_training:
                processed_frames.append(torch.zeros(3, *self.config.FRAME_SIZE))
            else:
                processed_frames.append(torch.zeros(3, *self.config.FRAME_SIZE))

        return torch.stack(processed_frames[:self.config.FRAMES_PER_VIDEO])

# ==================== DATASET LOADING ====================
def load_dataset_structure(data_path):
    """Load dataset with flexible structure"""
    print(f"Loading dataset from: {data_path}")

    video_paths = []
    labels = []

    if not os.path.exists(data_path):
        print(f"Dataset path does not exist: {data_path}")
        # Create test data
        create_test_dataset(data_path)
        return load_dataset_structure(data_path)

    # Common dataset structures
    structures = [
        # Structure 1: real/fake folders
        {
            'real': ['real', 'original', 'real_videos', 'originals'],
            'fake': ['fake', 'manipulated', 'fake_videos', 'fakes']
        },
        # Structure 2: train/val/test with real/fake subfolders
        {
            'real': ['train/real', 'val/real', 'test/real'],
            'fake': ['train/fake', 'val/fake', 'test/fake']
        }
    ]

    video_extensions = ['.mp4', '.avi', '.mov', '.mkv', '.webm', '.flv']

    for structure in structures:
        real_found = False
        fake_found = False

        for real_folder in structure['real']:
            real_path = os.path.join(data_path, real_folder)
            if os.path.exists(real_path):
                print(f"Found real videos in: {real_path}")
                real_found = True

                for ext in video_extensions:
                    for video_file in Path(real_path).glob(f'*{ext}'):
                        video_paths.append(str(video_file))
                        labels.append(0)
                    for video_file in Path(real_path).glob(f'*{ext.upper()}'):
                        video_paths.append(str(video_file))
                        labels.append(0)

        for fake_folder in structure['fake']:
            fake_path = os.path.join(data_path, fake_folder)
            if os.path.exists(fake_path):
                print(f"Found fake videos in: {fake_path}")
                fake_found = True

                for ext in video_extensions:
                    for video_file in Path(fake_path).glob(f'*{ext}'):
                        video_paths.append(str(video_file))
                        labels.append(1)
                    for video_file in Path(fake_path).glob(f'*{ext.upper()}'):
                        video_paths.append(str(video_file))
                        labels.append(1)

        if real_found or fake_found:
            break

    # If no videos found, search recursively
    if len(video_paths) == 0:
        print("Searching recursively for videos...")
        for root, dirs, files in os.walk(data_path):
            for file in files:
                if any(file.lower().endswith(ext) for ext in video_extensions):
                    video_path = os.path.join(root, file)
                    video_paths.append(video_path)

                    # Determine label from path
                    path_lower = video_path.lower()
                    if any(keyword in path_lower for keyword in ['real', 'original', 'authentic']):
                        labels.append(0)
                    elif any(keyword in path_lower for keyword in ['fake', 'manipulated', 'deepfake', 'morphed']):
                        labels.append(1)
                    else:
                        # Default to real
                        labels.append(0)

    print(f"\n📊 Dataset Statistics:")
    print(f"Total videos: {len(video_paths)}")
    print(f"Real videos: {labels.count(0)}")
    print(f"Fake videos: {labels.count(1)}")

    if len(video_paths) == 0:
        print("Creating test dataset...")
        create_test_dataset(data_path)
        return load_dataset_structure(data_path)

    return video_paths, labels

def create_test_dataset(data_path):
    """Create a test dataset if none exists"""
    import shutil

    test_real_path = os.path.join(data_path, 'real')
    test_fake_path = os.path.join(data_path, 'fake')

    os.makedirs(test_real_path, exist_ok=True)
    os.makedirs(test_fake_path, exist_ok=True)

    print(f"Created test dataset structure at: {data_path}")
    print(f"Real videos: {test_real_path}")
    print(f"Fake videos: {test_fake_path}")

    # Create dummy video files (text files as placeholders)
    for i in range(10):
        with open(os.path.join(test_real_path, f'real_{i:03d}.mp4.txt'), 'w') as f:
            f.write(f"Dummy real video {i}")

        with open(os.path.join(test_fake_path, f'fake_{i:03d}.mp4.txt'), 'w') as f:
            f.write(f"Dummy fake video {i}")

# ==================== DATASET CLASS ====================
class MorphedVideoDataset(Dataset):
    def __init__(self, video_paths, labels, preprocessor, is_training=True):
        self.video_paths = video_paths
        self.labels = labels
        self.preprocessor = preprocessor
        self.is_training = is_training

    def __len__(self):
        return len(self.video_paths)

    def __getitem__(self, idx):
        video_path = self.video_paths[idx]
        label = self.labels[idx]

        try:
            frames = self.preprocessor.preprocess_video(video_path, self.is_training)
            return frames, torch.tensor(label, dtype=torch.long), video_path
        except Exception as e:
            print(f"Error processing {video_path}: {e}")
            # Return dummy data
            dummy_frames = torch.zeros(
                self.preprocessor.config.FRAMES_PER_VIDEO,
                3,
                *self.preprocessor.config.FRAME_SIZE
            )
            return dummy_frames, torch.tensor(label, dtype=torch.long), video_path

# ==================== MODELS ====================
class EnhancedResNet(nn.Module):
    """Enhanced ResNet50 with temporal attention"""
    def __init__(self, config):
        super().__init__()
        self.config = config

        # Load pretrained ResNet50
        try:
            backbone = models.resnet50(pretrained=True)
        except:
            backbone = models.resnet50(weights='DEFAULT')

        # Remove final layers
        self.feature_extractor = nn.Sequential(*list(backbone.children())[:-2])

        # Global average pooling
        self.global_pool = nn.AdaptiveAvgPool2d((1, 1))

        # Temporal attention
        self.temporal_attention = nn.Sequential(
            nn.Linear(2048, 512),
            nn.ReLU(),
            nn.Dropout(config.DROPOUT),
            nn.Linear(512, config.FRAMES_PER_VIDEO),
            nn.Softmax(dim=1)
        )

        # Classification head
        self.classifier = nn.Sequential(
            nn.Linear(2048 * config.FRAMES_PER_VIDEO, 1024),
            nn.ReLU(),
            nn.Dropout(config.DROPOUT),
            nn.Linear(1024, 512),
            nn.ReLU(),
            nn.Dropout(config.DROPOUT),
            nn.Linear(512, config.NUM_CLASSES)
        )

    def forward(self, x):
        # x: [B, T, C, H, W]
        batch_size, timesteps, C, H, W = x.size()

        # Process each frame
        frame_features = []
        for t in range(timesteps):
            frame = x[:, t, :, :, :]
            features = self.feature_extractor(frame)
            features = self.global_pool(features)
            features = features.view(batch_size, -1)
            frame_features.append(features)

        # Stack features
        features = torch.stack(frame_features, dim=1)  # [B, T, 2048]

        # Apply temporal attention
        attention_weights = self.temporal_attention(features.mean(dim=2))  # [B, T]
        attention_weights = attention_weights.unsqueeze(2)  # [B, T, 1]
        weighted_features = features * attention_weights

        # Flatten for classification
        flattened = weighted_features.view(batch_size, -1)

        # Classification
        output = self.classifier(flattened)

        return output

class EnhancedEfficientNet(nn.Module):
    """Enhanced EfficientNet-B4 with spatial attention"""
    def __init__(self, config):
        super().__init__()
        self.config = config

        # Load pretrained EfficientNet-B4
        try:
            backbone = models.efficientnet_b4(pretrained=True)
        except:
            backbone = models.efficientnet_b4(weights='DEFAULT')

        # Remove final layers
        self.feature_extractor = nn.Sequential(*list(backbone.children())[:-2])

        # Get feature dimension
        self.feature_dim = 1792  # EfficientNet-B4 feature dimension

        # Spatial attention
        self.spatial_attention = nn.Sequential(
            nn.Conv2d(self.feature_dim, self.feature_dim // 16, kernel_size=1),
            nn.ReLU(),
            nn.Conv2d(self.feature_dim // 16, 1, kernel_size=1),
            nn.Sigmoid()
        )

        # Global pooling
        self.global_pool = nn.AdaptiveAvgPool2d((1, 1))

        # Classification head
        self.classifier = nn.Sequential(
            nn.Linear(self.feature_dim * config.FRAMES_PER_VIDEO, 1024),
            nn.ReLU(),
            nn.Dropout(config.DROPOUT),
            nn.Linear(1024, 512),
            nn.ReLU(),
            nn.Dropout(config.DROPOUT),
            nn.Linear(512, config.NUM_CLASSES)
        )

    def forward(self, x):
        # x: [B, T, C, H, W]
        batch_size, timesteps, C, H, W = x.size()

        # Process each frame
        frame_features = []
        for t in range(timesteps):
            frame = x[:, t, :, :, :]
            features = self.feature_extractor(frame)

            # Apply spatial attention
            attention_map = self.spatial_attention(features)
            attended_features = features * attention_map

            # Global pooling
            pooled = self.global_pool(attended_features)
            pooled = pooled.view(batch_size, -1)
            frame_features.append(pooled)

        # Concatenate all frame features
        features = torch.cat(frame_features, dim=1)

        # Classification
        output = self.classifier(features)

        return output

# ==================== TRAINER ====================
class ModelTrainer:
    def __init__(self, model, config, model_name):
        self.model = model.to(device)
        self.config = config
        self.model_name = model_name

        # Optimizer with weight decay
        self.optimizer = optim.AdamW(
            model.parameters(),
            lr=config.LEARNING_RATE,
            weight_decay=1e-4,
            betas=(0.9, 0.999)
        )

        # Loss function with class weights
        self.criterion = nn.CrossEntropyLoss()

        # Learning rate scheduler
        self.scheduler = optim.lr_scheduler.CosineAnnealingLR(
            self.optimizer,
            T_max=config.EPOCHS,
            eta_min=1e-6
        )

        # Early stopping
        self.best_accuracy = 0
        self.patience_counter = 0

        # Create save directory
        self.save_path = os.path.join(config.MODEL_PATH, model_name)
        os.makedirs(self.save_path, exist_ok=True)

    def train_epoch(self, train_loader, epoch):
        self.model.train()
        total_loss = 0
        correct = 0
        total = 0

        pbar = tqdm(train_loader, desc=f'Epoch {epoch+1}/{self.config.EPOCHS}')
        for batch_idx, (data, target, _) in enumerate(pbar):
            data, target = data.to(device), target.to(device)

            self.optimizer.zero_grad()
            output = self.model(data)
            loss = self.criterion(output, target)
            loss.backward()

            # Gradient clipping
            torch.nn.utils.clip_grad_norm_(self.model.parameters(), max_norm=1.0)

            self.optimizer.step()

            total_loss += loss.item()
            _, predicted = output.max(1)
            total += target.size(0)
            correct += predicted.eq(target).sum().item()

            pbar.set_postfix({
                'Loss': f'{loss.item():.4f}',
                'Acc': f'{100.*correct/total:.2f}%'
            })

        return total_loss / len(train_loader), 100. * correct / total

    def validate(self, val_loader):
        self.model.eval()
        total_loss = 0
        correct = 0
        total = 0
        all_preds = []
        all_targets = []
        all_probs = []

        with torch.no_grad():
            for data, target, _ in val_loader:
                data, target = data.to(device), target.to(device)
                output = self.model(data)
                loss = self.criterion(output, target)
                probs = F.softmax(output, dim=1)

                total_loss += loss.item()
                _, predicted = output.max(1)
                total += target.size(0)
                correct += predicted.eq(target).sum().item()

                all_preds.extend(predicted.cpu().numpy())
                all_targets.extend(target.cpu().numpy())
                all_probs.extend(probs.cpu().numpy())

        accuracy = 100. * correct / total
        return total_loss / len(val_loader), accuracy, all_preds, all_targets, all_probs

    def train(self, train_loader, val_loader):
        history = {
            'train_loss': [], 'train_acc': [],
            'val_loss': [], 'val_acc': [],
            'learning_rates': []
        }

        for epoch in range(self.config.EPOCHS):
            print(f'\n{"="*60}')
            print(f'Epoch {epoch+1}/{self.config.EPOCHS}')
            print(f'{"="*60}')

            train_loss, train_acc = self.train_epoch(train_loader, epoch)
            val_loss, val_acc, _, _, _ = self.validate(val_loader)

            # Update learning rate
            self.scheduler.step()
            current_lr = self.optimizer.param_groups[0]['lr']

            # Save history
            history['train_loss'].append(train_loss)
            history['train_acc'].append(train_acc)
            history['val_loss'].append(val_loss)
            history['val_acc'].append(val_acc)
            history['learning_rates'].append(current_lr)

            print(f'Train Loss: {train_loss:.4f}, Train Acc: {train_acc:.2f}%')
            print(f'Val Loss: {val_loss:.4f}, Val Acc: {val_acc:.2f}%')
            print(f'Learning Rate: {current_lr:.6f}')

            # Save best model
            if val_acc > self.best_accuracy:
                self.best_accuracy = val_acc
                self.patience_counter = 0

                torch.save({
                    'epoch': epoch,
                    'model_state_dict': self.model.state_dict(),
                    'optimizer_state_dict': self.optimizer.state_dict(),
                    'scheduler_state_dict': self.scheduler.state_dict(),
                    'accuracy': val_acc,
                    'loss': val_loss,
                    'config': self.config
                }, os.path.join(self.save_path, 'best_model.pth'))

                print(f'🚀 Best model saved with accuracy: {val_acc:.2f}%')
            else:
                self.patience_counter += 1

            # Early stopping
            if self.patience_counter >= self.config.PATIENCE:
                print(f'⏹️ Early stopping at epoch {epoch+1}')
                break

        # Load best model
        best_model_path = os.path.join(self.save_path, 'best_model.pth')
        if os.path.exists(best_model_path):
            checkpoint = torch.load(best_model_path, map_location=device)
            self.model.load_state_dict(checkpoint['model_state_dict'])

        return history

    def evaluate(self, test_loader):
        self.model.eval()
        all_preds = []
        all_targets = []
        all_probs = []

        with torch.no_grad():
            for data, target, _ in test_loader:
                data, target = data.to(device), target.to(device)
                output = self.model(data)
                probs = F.softmax(output, dim=1)

                _, predicted = output.max(1)

                all_preds.extend(predicted.cpu().numpy())
                all_targets.extend(target.cpu().numpy())
                all_probs.extend(probs.cpu().numpy())

        return all_preds, all_targets, all_probs

# ==================== LOAD DATASET ====================
print("\n" + "="*60)
print("LOADING DATASET")
print("="*60)

video_paths, labels = load_dataset_structure(config.DATA_PATH)

print(f"\n✅ Successfully loaded {len(video_paths)} videos")

# ==================== DATA SPLITTING ====================
print(f"\nSplitting dataset...")

# Stratified split
train_paths, test_paths, train_labels, test_labels = train_test_split(
    video_paths, labels, test_size=0.2, stratify=labels, random_state=42
)

train_paths, val_paths, train_labels, val_labels = train_test_split(
    train_paths, train_labels, test_size=0.2, stratify=train_labels, random_state=42
)

print(f"Train: {len(train_paths)} videos")
print(f"Validation: {len(val_paths)} videos")
print(f"Test: {len(test_paths)} videos")
print(f"Train - Real: {train_labels.count(0)}, Fake: {train_labels.count(1)}")
print(f"Val - Real: {val_labels.count(0)}, Fake: {val_labels.count(1)}")
print(f"Test - Real: {test_labels.count(0)}, Fake: {test_labels.count(1)}")

# ==================== CREATE DATALOADERS ====================
print("\nCreating dataloaders...")
preprocessor = EnhancedVideoPreprocessor(config)

train_dataset = MorphedVideoDataset(train_paths, train_labels, preprocessor, is_training=True)
val_dataset = MorphedVideoDataset(val_paths, val_labels, preprocessor, is_training=False)
test_dataset = MorphedVideoDataset(test_paths, test_labels, preprocessor, is_training=False)

# Adjust batch size based on dataset size
batch_size = min(config.BATCH_SIZE, len(train_dataset))

train_loader = DataLoader(
    train_dataset,
    batch_size=batch_size,
    shuffle=True,
    num_workers=2,
    pin_memory=True if torch.cuda.is_available() else False
)

val_loader = DataLoader(
    val_dataset,
    batch_size=batch_size,
    shuffle=False,
    num_workers=2,
    pin_memory=True if torch.cuda.is_available() else False
)

test_loader = DataLoader(
    test_dataset,
    batch_size=batch_size,
    shuffle=False,
    num_workers=2,
    pin_memory=True if torch.cuda.is_available() else False
)

# ==================== TRAIN RESNET MODEL ====================
print(f"\n{'='*60}")
print("TRAINING ENHANCED RESNET MODEL")
print(f"{'='*60}")
resnet_model = EnhancedResNet(config)
print(f"ResNet Parameters: {sum(p.numel() for p in resnet_model.parameters()):,}")

resnet_trainer = ModelTrainer(resnet_model, config, 'Enhanced_ResNet')
resnet_history = resnet_trainer.train(train_loader, val_loader)

# Evaluate ResNet
resnet_preds, resnet_targets, resnet_probs = resnet_trainer.evaluate(test_loader)
resnet_accuracy = accuracy_score(resnet_targets, resnet_preds)

# Calculate detailed metrics
resnet_cm = confusion_matrix(resnet_targets, resnet_preds)
resnet_report = classification_report(resnet_targets, resnet_preds,
                                     target_names=['Real', 'Fake'], output_dict=True)

try:
    resnet_auc = roc_auc_score(resnet_targets, [p[1] for p in resnet_probs])
except:
    resnet_auc = 0.5

# Calculate F1 scores
resnet_precision, resnet_recall, resnet_f1, _ = precision_recall_fscore_support(
    resnet_targets, resnet_preds, average='binary'
)

print(f"\n📊 ResNet Results:")
print(f"Accuracy: {resnet_accuracy:.4f}")
print(f"AUC: {resnet_auc:.4f}")
print(f"Precision: {resnet_precision:.4f}")
print(f"Recall: {resnet_recall:.4f}")
print(f"F1-Score: {resnet_f1:.4f}")
print(f"Confusion Matrix:\n{resnet_cm}")

# ==================== TRAIN EFFICIENTNET MODEL ====================
print(f"\n{'='*60}")
print("TRAINING ENHANCED EFFICIENTNET MODEL")
print(f"{'='*60}")

efficientnet_model = EnhancedEfficientNet(config)
print(f"EfficientNet Parameters: {sum(p.numel() for p in efficientnet_model.parameters()):,}")

eff_trainer = ModelTrainer(efficientnet_model, config, 'Enhanced_EfficientNet')
eff_history = eff_trainer.train(train_loader, val_loader)

# Evaluate EfficientNet
eff_preds, eff_targets, eff_probs = eff_trainer.evaluate(test_loader)
eff_accuracy = accuracy_score(eff_targets, eff_preds)

# Calculate detailed metrics
eff_cm = confusion_matrix(eff_targets, eff_preds)
eff_report = classification_report(eff_targets, eff_preds,
                                 target_names=['Real', 'Fake'], output_dict=True)

try:
    eff_auc = roc_auc_score(eff_targets, [p[1] for p in eff_probs])
except:
    eff_auc = 0.5

# Calculate F1 scores
eff_precision, eff_recall, eff_f1, _ = precision_recall_fscore_support(
    eff_targets, eff_preds, average='binary'
)

print(f"\n📊 EfficientNet Results:")
print(f"Accuracy: {eff_accuracy:.4f}")
print(f"AUC: {eff_auc:.4f}")
print(f"Precision: {eff_precision:.4f}")
print(f"Recall: {eff_recall:.4f}")
print(f"F1-Score: {eff_f1:.4f}")
print(f"Confusion Matrix:\n{eff_cm}")

# ==================== VISUALIZATION ====================
def plot_training_history(history, model_name):
    """Plot training history"""
    fig, axes = plt.subplots(2, 2, figsize=(15, 10))

    # Loss
    axes[0, 0].plot(history['train_loss'], label='Train Loss', linewidth=2)
    axes[0, 0].plot(history['val_loss'], label='Val Loss', linewidth=2)
    axes[0, 0].set_title(f'{model_name} - Loss')
    axes[0, 0].set_xlabel('Epoch')
    axes[0, 0].set_ylabel('Loss')
    axes[0, 0].legend()
    axes[0, 0].grid(True, alpha=0.3)

    # Accuracy
    axes[0, 1].plot(history['train_acc'], label='Train Acc', linewidth=2)
    axes[0, 1].plot(history['val_acc'], label='Val Acc', linewidth=2)
    axes[0, 1].set_title(f'{model_name} - Accuracy')
    axes[0, 1].set_xlabel('Epoch')
    axes[0, 1].set_ylabel('Accuracy (%)')
    axes[0, 1].legend()
    axes[0, 1].grid(True, alpha=0.3)

    # Learning rate
    axes[1, 0].plot(history['learning_rates'], linewidth=2, color='purple')
    axes[1, 0].set_title(f'{model_name} - Learning Rate')
    axes[1, 0].set_xlabel('Epoch')
    axes[1, 0].set_ylabel('Learning Rate')
    axes[1, 0].grid(True, alpha=0.3)
    axes[1, 0].set_yscale('log')

    # Combined plot
    epochs = range(1, len(history['train_loss']) + 1)
    axes[1, 1].plot(epochs, history['train_acc'], 'b-', label='Train Acc', alpha=0.7)
    axes[1, 1].plot(epochs, history['val_acc'], 'r-', label='Val Acc', alpha=0.7)
    axes[1, 1].fill_between(epochs,
                           np.array(history['train_acc']) - np.array(history['train_acc']).std(),
                           np.array(history['train_acc']) + np.array(history['train_acc']).std(),
                           alpha=0.2, color='blue')
    axes[1, 1].fill_between(epochs,
                           np.array(history['val_acc']) - np.array(history['val_acc']).std(),
                           np.array(history['val_acc']) + np.array(history['val_acc']).std(),
                           alpha=0.2, color='red')
    axes[1, 1].set_title(f'{model_name} - Accuracy with Std Dev')
    axes[1, 1].set_xlabel('Epoch')
    axes[1, 1].set_ylabel('Accuracy (%)')
    axes[1, 1].legend()
    axes[1, 1].grid(True, alpha=0.3)

    plt.tight_layout()
    plt.savefig(os.path.join(config.RESULTS_PATH, f'{model_name}_training_history.png'),
                dpi=300, bbox_inches='tight')
    plt.show()

# Plot training history
plot_training_history(resnet_history, 'ResNet')
plot_training_history(eff_history, 'EfficientNet')

# ==================== MODEL COMPARISON ====================
def plot_model_comparison(resnet_metrics, eff_metrics):
    """Plot comparison of model results"""
    fig, axes = plt.subplots(2, 3, figsize=(18, 12))

    # Accuracy comparison
    models = ['ResNet', 'EfficientNet']
    metrics = ['Accuracy', 'AUC', 'F1-Score', 'Precision', 'Recall']

    # Bar colors
    colors = ['skyblue', 'lightcoral']

    # Plot metrics
    metric_data = [
        [resnet_metrics['accuracy'], eff_metrics['accuracy']],
        [resnet_metrics['auc'], eff_metrics['auc']],
        [resnet_metrics['f1'], eff_metrics['f1']],
        [resnet_metrics['precision'], eff_metrics['precision']],
        [resnet_metrics['recall'], eff_metrics['recall']]
    ]

    for idx, (metric, data) in enumerate(zip(metrics, metric_data)):
        row = idx // 3
        col = idx % 3

        bars = axes[row, col].bar(models, data, color=colors, edgecolor='black', linewidth=2)
        axes[row, col].set_title(f'{metric} Comparison')
        axes[row, col].set_ylabel(metric)
        axes[row, col].grid(True, alpha=0.3, axis='y')

        if metric in ['Accuracy', 'Precision', 'Recall']:
            axes[row, col].set_ylim(0, 1)
        elif metric == 'AUC':
            axes[row, col].set_ylim(0, 1)
        elif metric == 'F1-Score':
            axes[row, col].set_ylim(0, 1)

        for bar, value in zip(bars, data):
            axes[row, col].text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.01,
                               f'{value:.3f}', ha='center', va='bottom', fontweight='bold')

    # Confusion matrices
    axes[1, 2].axis('off')

    # Create separate figure for confusion matrices
    fig2, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))

    # ResNet confusion matrix
    im1 = ax1.imshow(resnet_cm, cmap='Blues', interpolation='nearest')
    ax1.set_title('ResNet Confusion Matrix')
    for i in range(resnet_cm.shape[0]):
        for j in range(resnet_cm.shape[1]):
            ax1.text(j, i, f'{resnet_cm[i, j]}',
                    ha='center', va='center',
                    color='white' if resnet_cm[i, j] > resnet_cm.max()/2 else 'black',
                    fontsize=12, fontweight='bold')
    ax1.set_xticks([0, 1])
    ax1.set_yticks([0, 1])
    ax1.set_xticklabels(['Real', 'Fake'])
    ax1.set_yticklabels(['Real', 'Fake'])
    ax1.set_ylabel('True Label')
    ax1.set_xlabel('Predicted Label')

    # EfficientNet confusion matrix
    im2 = ax2.imshow(eff_cm, cmap='Oranges', interpolation='nearest')
    ax2.set_title('EfficientNet Confusion Matrix')
    for i in range(eff_cm.shape[0]):
        for j in range(eff_cm.shape[1]):
            ax2.text(j, i, f'{eff_cm[i, j]}',
                    ha='center', va='center',
                    color='white' if eff_cm[i, j] > eff_cm.max()/2 else 'black',
                    fontsize=12, fontweight='bold')
    ax2.set_xticks([0, 1])
    ax2.set_yticks([0, 1])
    ax2.set_xticklabels(['Real', 'Fake'])
    ax2.set_yticklabels(['Real', 'Fake'])
    ax2.set_ylabel('True Label')
    ax2.set_xlabel('Predicted Label')

    plt.tight_layout()
    plt.savefig(os.path.join(config.RESULTS_PATH, 'confusion_matrices.png'),
                dpi=300, bbox_inches='tight')
    plt.show()

    plt.tight_layout()
    plt.savefig(os.path.join(config.RESULTS_PATH, 'model_comparison.png'),
                dpi=300, bbox_inches='tight')
    plt.show()

    # ROC Curves
    fig3, ax = plt.subplots(figsize=(10, 8))

    from sklearn.metrics import roc_curve

    # ResNet ROC
    fpr_resnet, tpr_resnet, _ = roc_curve(resnet_targets, [p[1] for p in resnet_probs])
    ax.plot(fpr_resnet, tpr_resnet, label=f'ResNet (AUC = {resnet_auc:.3f})',
            linewidth=3, color='blue')

    # EfficientNet ROC
    fpr_eff, tpr_eff, _ = roc_curve(eff_targets, [p[1] for p in eff_probs])
    ax.plot(fpr_eff, tpr_eff, label=f'EfficientNet (AUC = {eff_auc:.3f})',
            linewidth=3, color='red')

    # Random classifier
    ax.plot([0, 1], [0, 1], 'k--', label='Random', linewidth=2, alpha=0.5)

    ax.set_xlabel('False Positive Rate', fontsize=12)
    ax.set_ylabel('True Positive Rate', fontsize=12)
    ax.set_title('ROC Curves', fontsize=14, fontweight='bold')
    ax.legend(loc='lower right', fontsize=12)
    ax.grid(True, alpha=0.3)
    ax.set_xlim([0.0, 1.0])
    ax.set_ylim([0.0, 1.05])

    plt.tight_layout()
    plt.savefig(os.path.join(config.RESULTS_PATH, 'roc_curves.png'),
                dpi=300, bbox_inches='tight')
    plt.show()

# Prepare metrics for comparison
resnet_metrics = {
    'accuracy': resnet_accuracy,
    'auc': resnet_auc,
    'f1': resnet_f1,
    'precision': resnet_precision,
    'recall': resnet_recall
}

eff_metrics = {
    'accuracy': eff_accuracy,
    'auc': eff_auc,
    'f1': eff_f1,
    'precision': eff_precision,
    'recall': eff_recall
}

# Plot comparison
plot_model_comparison(resnet_metrics, eff_metrics)

# ==================== VIDEO UPLOAD AND PREDICTION SYSTEM ====================
class VideoMorphingDetector:
    def __init__(self, config, model_choice='ensemble'):
        self.config = config
        self.preprocessor = EnhancedVideoPreprocessor(config)
        self.model_choice = model_choice

        # Load models
        self.resnet_model = self._load_model('Enhanced_ResNet')
        self.eff_model = self._load_model('Enhanced_EfficientNet')

        print("✅ Models loaded successfully!")

    def _load_model(self, model_name):
        """Load trained model"""
        model_path = os.path.join(self.config.MODEL_PATH, model_name, 'best_model.pth')

        if model_name == 'Enhanced_ResNet':
            model = EnhancedResNet(config)
        else:
            model = EnhancedEfficientNet(config)

        if os.path.exists(model_path):
            checkpoint = torch.load(model_path, map_location=device)
            model.load_state_dict(checkpoint['model_state_dict'])
            model.to(device)
            model.eval()
            print(f"✅ Loaded {model_name}")
        else:
            print(f"⚠️ No trained {model_name} found, using untrained model")
            model.to(device)
            model.eval()

        return model

    def predict_video(self, video_path):
        """Predict if a video is morphed or not"""
        if not os.path.exists(video_path):
            return {
                'error': 'Video file not found',
                'prediction': 'ERROR',
                'confidence': 0.0
            }

        try:
            # Preprocess video
            frames = self.preprocessor.preprocess_video(video_path, is_training=False)
            frames = frames.unsqueeze(0).to(device)

            predictions = []
            confidences = []

            # Get prediction from ResNet
            with torch.no_grad():
                resnet_output = self.resnet_model(frames)
                resnet_probs = F.softmax(resnet_output, dim=1)
                resnet_pred = torch.argmax(resnet_probs, dim=1).item()
                resnet_conf = resnet_probs[0][resnet_pred].item()
                predictions.append(resnet_pred)
                confidences.append(resnet_conf)

                # Get prediction from EfficientNet
                eff_output = self.eff_model(frames)
                eff_probs = F.softmax(eff_output, dim=1)
                eff_pred = torch.argmax(eff_probs, dim=1).item()
                eff_conf = eff_probs[0][eff_pred].item()
                predictions.append(eff_pred)
                confidences.append(eff_conf)

            # Ensemble prediction
            if self.model_choice == 'ensemble':
                # Weighted average based on confidence
                total_conf = sum(confidences)
                weighted_pred = sum(p * c for p, c in zip(predictions, confidences)) / total_conf
                final_pred = 1 if weighted_pred > 0.5 else 0
                final_conf = weighted_pred if final_pred == 1 else 1 - weighted_pred
            elif self.model_choice == 'resnet':
                final_pred = predictions[0]
                final_conf = confidences[0]
            else:  # efficientnet
                final_pred = predictions[1]
                final_conf = confidences[1]

            # Interpret result
            label = "MORPHED/FAKE" if final_pred == 1 else "REAL/AUTHENTIC"

            return {
                'prediction': label,
                'confidence': float(final_conf * 100),
                'real_probability': float((1 - weighted_pred) * 100) if self.model_choice == 'ensemble' else float((1 - final_conf) * 100),
                'fake_probability': float(weighted_pred * 100) if self.model_choice == 'ensemble' else float(final_conf * 100),
                'resnet_prediction': 'FAKE' if predictions[0] == 1 else 'REAL',
                'resnet_confidence': float(confidences[0] * 100),
                'efficientnet_prediction': 'FAKE' if predictions[1] == 1 else 'REAL',
                'efficientnet_confidence': float(confidences[1] * 100)
            }

        except Exception as e:
            return {
                'error': str(e),
                'prediction': 'ERROR',
                'confidence': 0.0
            }

    def visualize_prediction(self, video_path, result):
        """Visualize prediction results"""
        fig, axes = plt.subplots(2, 3, figsize=(15, 10))

        # Extract first frame for visualization
        cap = cv2.VideoCapture(video_path)
        ret, frame = cap.read()
        cap.release()

        if ret:
            # Original frame
            axes[0, 0].imshow(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB))
            axes[0, 0].set_title('Original Video Frame')
            axes[0, 0].axis('off')

            # Try to detect and show face
            bbox = self.preprocessor.step2_face_detection_ensemble(frame)
            if bbox:
                x, y, w, h = bbox
                frame_with_bbox = frame.copy()
                cv2.rectangle(frame_with_bbox, (x, y), (x+w, y+h), (0, 255, 0), 2)
                axes[0, 1].imshow(cv2.cvtColor(frame_with_bbox, cv2.COLOR_BGR2RGB))
                axes[0, 1].set_title('Face Detection')
            else:
                axes[0, 1].imshow(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB))
                axes[0, 1].set_title('No Face Detected')
            axes[0, 1].axis('off')

        # Prediction probabilities bar chart
        labels = ['Real', 'Fake']
        probabilities = [result['real_probability'], result['fake_probability']]
        colors = ['green' if result['prediction'] == 'REAL/AUTHENTIC' else 'lightgreen',
                 'red' if result['prediction'] == 'MORPHED/FAKE' else 'lightcoral']

        bars = axes[0, 2].bar(labels, probabilities, color=colors, edgecolor='black', linewidth=2)
        axes[0, 2].set_ylabel('Probability (%)')
        axes[0, 2].set_title(f'Final Prediction: {result["prediction"]}')
        axes[0, 2].set_ylim(0, 100)
        axes[0, 2].grid(True, alpha=0.3, axis='y')

        for bar, prob in zip(bars, probabilities):
            axes[0, 2].text(bar.get_x() + bar.get_width()/2, bar.get_height() + 1,
                           f'{prob:.1f}%', ha='center', va='bottom', fontweight='bold')

        # Model comparison
        model_names = ['ResNet', 'EfficientNet']
        model_predictions = [result['resnet_prediction'], result['efficientnet_prediction']]
        model_confidences = [result['resnet_confidence'], result['efficientnet_confidence']]
        model_colors = []

        for pred in model_predictions:
            if pred == 'REAL':
                model_colors.append('lightgreen')
            else:
                model_colors.append('lightcoral')

        x_pos = np.arange(len(model_names))
        bars2 = axes[1, 0].bar(x_pos, model_confidences, color=model_colors, edgecolor='black', linewidth=2)
        axes[1, 0].set_ylabel('Confidence (%)')
        axes[1, 0].set_title('Model Predictions')
        axes[1, 0].set_xticks(x_pos)
        axes[1, 0].set_xticklabels(model_names)
        axes[1, 0].set_ylim(0, 100)
        axes[1, 0].grid(True, alpha=0.3, axis='y')

        for bar, conf, pred in zip(bars2, model_confidences, model_predictions):
            axes[1, 0].text(bar.get_x() + bar.get_width()/2, bar.get_height() + 1,
                           f'{pred}\n{conf:.1f}%', ha='center', va='bottom', fontweight='bold')

        # Confidence gauge
        axes[1, 1].axis('off')
        self._draw_confidence_gauge(axes[1, 1], result['confidence'], result['prediction'])

        # Text summary
        axes[1, 2].axis('off')
        summary_text = f"""
        📊 FINAL RESULT:
        -------------------------
        Prediction: {result['prediction']}
        Confidence: {result['confidence']:.2f}%

        📈 MODEL DETAILS:
        -------------------------
        ResNet: {result['resnet_prediction']} ({result['resnet_confidence']:.1f}%)
        EfficientNet: {result['efficientnet_prediction']} ({result['efficientnet_confidence']:.1f}%)

        ⚠️ INTERPRETATION:
        -------------------------
        {'⚠️ This video appears to be MORPHED/FAKE!' if result['prediction'] == 'MORPHED/FAKE' else '✅ This video appears to be REAL/AUTHENTIC!'}

        Confidence Level: {'High' if result['confidence'] > 80 else 'Medium' if result['confidence'] > 60 else 'Low'}
        """

        axes[1, 2].text(0.1, 0.5, summary_text, transform=axes[1, 2].transAxes,
                       fontsize=10, verticalalignment='center',
                       bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.5))

        plt.tight_layout()
        plt.savefig(os.path.join(config.RESULTS_PATH, 'prediction_visualization.png'),
                   dpi=300, bbox_inches='tight')
        plt.show()

    def _draw_confidence_gauge(self, ax, confidence, prediction):
        """Draw a confidence gauge"""
        # Create gauge
        theta = np.linspace(0, np.pi, 100)
        r = 2

        # Background arc
        ax.plot(theta, np.ones_like(theta) * r, 'k-', linewidth=5, alpha=0.2)

        # Confidence arc
        conf_rad = (confidence / 100) * np.pi
        theta_conf = np.linspace(0, conf_rad, 100)
        color = 'red' if prediction == 'MORPHED/FAKE' else 'green'
        ax.plot(theta_conf, np.ones_like(theta_conf) * r, color=color, linewidth=8)

        # Needle
        needle_length = 1.8
        ax.plot([conf_rad, conf_rad], [0, needle_length], 'k-', linewidth=3)

        # Labels
        ax.text(np.pi/2, 2.2, f'{confidence:.1f}%', ha='center', va='center',
               fontsize=16, fontweight='bold')
        ax.text(0, 1.5, '0%', ha='center', va='center')
        ax.text(np.pi, 1.5, '100%', ha='center', va='center')

        ax.set_xlim(0, np.pi)
        ax.set_ylim(0, 2.5)
        ax.set_aspect('equal')
        ax.axis('off')
        ax.set_title('Confidence Gauge', fontsize=12, fontweight='bold')

# ==================== TEST WITH SAMPLE VIDEO ====================
print(f"\n{'='*60}")
print("TESTING PREDICTION SYSTEM")
print(f"{'='*60}")

# Initialize detector
detector = VideoMorphingDetector(config, model_choice='ensemble')

# Test with a sample video from test set if available
if test_paths:
    test_video = test_paths[0]
    print(f"Testing with: {os.path.basename(test_video)}")

    result = detector.predict_video(test_video)

    if 'error' in result:
        print(f"❌ Error: {result['error']}")
    else:
        print(f"\n🎯 PREDICTION RESULT:")
        print(f"Prediction: {result['prediction']}")
        print(f"Confidence: {result['confidence']:.2f}%")
        print(f"Real Probability: {result['real_probability']:.2f}%")
        print(f"Fake Probability: {result['fake_probability']:.2f}%")
        print(f"\n📊 MODEL DETAILS:")
        print(f"ResNet: {result['resnet_prediction']} ({result['resnet_confidence']:.1f}%)")
        print(f"EfficientNet: {result['efficientnet_prediction']} ({result['efficientnet_confidence']:.1f}%)")

        # Visualize prediction
        detector.visualize_prediction(test_video, result)
else:
    print("No test videos available for demonstration")

# ==================== VIDEO UPLOAD INTERFACE ====================
def upload_and_test_video():
    """Upload a video and test it"""
    print(f"\n{'='*60}")
    print("VIDEO UPLOAD AND TESTING INTERFACE")
    print(f"{'='*60}")

    if IN_COLAB:
        print("\n📤 Upload a video file for testing...")
        uploaded = files.upload()

        if uploaded:
            for filename in uploaded.keys():
                print(f"✅ Uploaded: {filename}")

                # Save uploaded file
                video_path = os.path.join('/content', filename)
                with open(video_path, 'wb') as f:
                    f.write(uploaded[filename])

                # Analyze video
                print(f"\n🔍 Analyzing {filename}...")
                result = detector.predict_video(video_path)

                if 'error' in result:
                    print(f"❌ Error: {result['error']}")
                else:
                    print(f"\n🎯 ANALYSIS RESULTS:")
                    print(f"Prediction: {result['prediction']}")
                    print(f"Confidence: {result['confidence']:.2f}%")
                    print(f"Real Probability: {result['real_probability']:.2f}%")
                    print(f"Fake Probability: {result['fake_probability']:.2f}%")

                    # Visualize
                    detector.visualize_prediction(video_path, result)
        else:
            print("❌ No file uploaded!")
    else:
        print("\n📁 Local file testing...")
        print("Please specify the path to your video file:")
        video_path = input("Video path: ").strip()

        if os.path.exists(video_path):
            print(f"🔍 Analyzing {os.path.basename(video_path)}...")
            result = detector.predict_video(video_path)

            if 'error' in result:
                print(f"❌ Error: {result['error']}")
            else:
                print(f"\n🎯 ANALYSIS RESULTS:")
                print(f"Prediction: {result['prediction']}")
                print(f"Confidence: {result['confidence']:.2f}%")
                print(f"Real Probability: {result['real_probability']:.2f}%")
                print(f"Fake Probability: {result['fake_probability']:.2f}%")

                # Visualize
                detector.visualize_prediction(video_path, result)
        else:
            print(f"❌ File not found: {video_path}")

# ==================== FINAL SUMMARY ====================
print(f"\n{'='*60}")
print("SYSTEM SUMMARY")
print(f"{'='*60}")

print("\n📊 MODEL PERFORMANCE SUMMARY:")
print(f"{'-'*40}")
print(f"ResNet Accuracy: {resnet_accuracy:.4f}")
print(f"ResNet F1-Score: {resnet_f1:.4f}")
print(f"ResNet AUC: {resnet_auc:.4f}")
print(f"{'-'*40}")
print(f"EfficientNet Accuracy: {eff_accuracy:.4f}")
print(f"EfficientNet F1-Score: {eff_f1:.4f}")
print(f"EfficientNet AUC: {eff_auc:.4f}")
print(f"{'-'*40}")

# Determine best model
if resnet_accuracy > eff_accuracy:
    print(f"🏆 BEST MODEL: ResNet (by accuracy)")
elif eff_accuracy > resnet_accuracy:
    print(f"🏆 BEST MODEL: EfficientNet (by accuracy)")
else:
    if resnet_f1 > eff_f1:
        print(f"🏆 BEST MODEL: ResNet (by F1-Score)")
    else:
        print(f"🏆 BEST MODEL: EfficientNet (by F1-Score)")

print(f"\n{'='*60}")
print("SYSTEM READY FOR USE!")
print(f"{'='*60}")

print("\n📋 USAGE INSTRUCTIONS:")
print("1. To test a video, run: upload_and_test_video()")
print("2. To use the detector directly:")
print("   detector = VideoMorphingDetector(config)")
print("   result = detector.predict_video('your_video.mp4')")
print("3. To visualize results:")
print("   detector.visualize_prediction('your_video.mp4', result)")

print(f"\n💾 Models saved in: {config.MODEL_PATH}")
print(f"📈 Results saved in: {config.RESULTS_PATH}")

# Create a test function
def test_system():
    """Test the system with the upload interface"""
    upload_and_test_video()

print(f"\n🚀 Run 'test_system()' to test with your own video!")
print(f"{'='*60}")