# -*- coding: utf-8 -*-
"""attention based gated

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wCPriE3T-mJKHKMRFGzf4MMSQ5a1wG8S
"""

import re
import torch
import torch.nn as nn
import pandas as pd
import numpy as np

from torch.utils.data import Dataset, DataLoader
from transformers import RobertaTokenizer, RobertaModel
from torch.optim import AdamW
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report

def preprocess_text(text):
    text = text.lower()
    text = re.sub(r"http\S+|www\S+", "", text)      # remove URLs
    text = re.sub(r"@\w+", "", text)                # remove mentions
    text = re.sub(r"#(\w+)", r"\1", text)           # keep hashtag word
    text = re.sub(r"\d+", "", text)                 # remove numbers
    text = re.sub(r"\s+", " ", text).strip()        # extra spaces
    return text

def load_dataset(file_path):
    df = pd.read_csv(file_path)

    # auto-detect columns
    text_col = [c for c in df.columns if c.lower() in ["text", "tweet", "sentence", "content"]][0]
    label_col = [c for c in df.columns if c.lower() in ["label", "class", "category"]][0]

    df = df[[text_col, label_col]]
    df.columns = ["text", "label"]

    # encode labels if needed
    if df["label"].dtype == object:
        le = LabelEncoder()
        df["label"] = le.fit_transform(df["label"])
        print("Label Mapping:", dict(zip(le.classes_, le.transform(le.classes_))))

    df["text"] = df["text"].astype(str).apply(preprocess_text)
    return df

def split_dataset(df, test_size=0.2):
    return train_test_split(
        df,
        test_size=test_size,
        random_state=42,
        stratify=df["label"]
    )

class HateSpeechDataset(Dataset):
    def __init__(self, dataframe, tokenizer, max_len=128):
        self.df = dataframe.reset_index(drop=True)
        self.tokenizer = tokenizer
        self.max_len = max_len

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        text = self.df.loc[idx, "text"]
        label = self.df.loc[idx, "label"]

        encoding = self.tokenizer(
            text,
            max_length=self.max_len,
            padding="max_length",
            truncation=True,
            return_tensors="pt"
        )

        return {
            "input_ids": encoding["input_ids"].squeeze(0),
            "attention_mask": encoding["attention_mask"].squeeze(0),
            "labels": torch.tensor(label, dtype=torch.long)
        }

class SelfAttention(nn.Module):
    def __init__(self, hidden_dim):
        super().__init__()
        self.attn = nn.Linear(hidden_dim, 1)

    def forward(self, x):
        weights = torch.softmax(self.attn(x), dim=1)
        return torch.sum(weights * x, dim=1)

class CNNEncoder(nn.Module):
    def __init__(self, embed_dim, filters=128):
        super().__init__()
        self.convs = nn.ModuleList([
            nn.Conv1d(embed_dim, filters, k) for k in [3, 4, 5]
        ])

    def forward(self, x):
        x = x.permute(0, 2, 1)
        out = [torch.relu(conv(x)).max(dim=2)[0] for conv in self.convs]
        return torch.cat(out, dim=1)

class AttentionGatedFusionModel(nn.Module):
    def __init__(self, num_classes=3):
        super().__init__()

        self.roberta = RobertaModel.from_pretrained("roberta-base")
        hidden = self.roberta.config.hidden_size

        self.bilstm = nn.LSTM(hidden, 128, batch_first=True, bidirectional=True)
        self.cnn = CNNEncoder(hidden)

        self.att_r = SelfAttention(hidden)
        self.att_l = SelfAttention(256)

        self.gate_r = nn.Linear(hidden, hidden)
        self.gate_l = nn.Linear(256, 256)
        self.gate_c = nn.Linear(384, 384)

        self.classifier = nn.Sequential(
            nn.Linear(hidden + 256 + 384, 256),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(256, num_classes)
        )

    def forward(self, input_ids, attention_mask):
        roberta_out = self.roberta(input_ids, attention_mask).last_hidden_state

        r = self.att_r(roberta_out)
        l, _ = self.bilstm(roberta_out)
        l = self.att_l(l)
        c = self.cnn(roberta_out)

        r = torch.sigmoid(self.gate_r(r)) * r
        l = torch.sigmoid(self.gate_l(l)) * l
        c = torch.sigmoid(self.gate_c(c)) * c

        fused = torch.cat([r, l, c], dim=1)
        return self.classifier(fused)

def train_one_epoch(model, loader, optimizer, loss_fn, device):
    model.train()
    total_loss = 0

    for batch in loader:
        optimizer.zero_grad()

        outputs = model(
            batch["input_ids"].to(device),
            batch["attention_mask"].to(device)
        )

        loss = loss_fn(outputs, batch["labels"].to(device))
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    return total_loss / len(loader)

def evaluate(model, loader, device):
    model.eval()
    preds, labels = [], []

    with torch.no_grad():
        for batch in loader:
            outputs = model(
                batch["input_ids"].to(device),
                batch["attention_mask"].to(device)
            )
            preds.extend(torch.argmax(outputs, dim=1).cpu().numpy())
            labels.extend(batch["labels"].numpy())

    print(classification_report(labels, preds))

def main():
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    tokenizer = RobertaTokenizer.from_pretrained("roberta-base")

    df = load_dataset("/content/Twitter_HateSpeech.csv")
    train_df, test_df = split_dataset(df)

    train_ds = HateSpeechDataset(train_df, tokenizer)
    test_ds = HateSpeechDataset(test_df, tokenizer)

    train_loader = DataLoader(train_ds, batch_size=16, shuffle=True)
    test_loader = DataLoader(test_ds, batch_size=16)

    model = AttentionGatedFusionModel().to(device)

    optimizer = AdamW(model.parameters(), lr=2e-5)
    loss_fn = nn.CrossEntropyLoss()

    best_loss = float("inf")

    for epoch in range(5):
      loss = train_one_epoch(model, train_loader, optimizer, loss_fn, device)
      print(f"Epoch {epoch+1} Loss: {loss:.4f}")

      if loss < best_loss:
        best_loss = loss
        torch.save(model.state_dict(), "attention_gated_best.pt")
        print("✅ Best model saved")

    evaluate(model, test_loader, device)

if __name__ == "__main__":
    main()