# -*- coding: utf-8 -*-
"""ensemble soft vote

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KQNBCvcWgP0TKeC0uPMTijQTHi6nGTU4
"""

!pip install -q torch transformers scikit-learn pandas

import torch
import torch.nn as nn
import numpy as np
import pandas as pd

from torch.utils.data import Dataset, DataLoader
from transformers import RobertaTokenizer, RobertaModel
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, f1_score

df = pd.read_csv("/content/Twitter_HateSpeech.csv")

texts = df["tweet"].tolist()
labels = df["class"].tolist()

label_encoder = LabelEncoder()
labels = label_encoder.fit_transform(labels)

NUM_CLASSES = len(label_encoder.classes_)

X_train, X_test, y_train, y_test = train_test_split(
    texts, labels, test_size=0.2, stratify=labels, random_state=42
)

tokenizer = RobertaTokenizer.from_pretrained("roberta-base")

class TextDataset(Dataset):
    def __init__(self, texts, labels, tokenizer, max_len=128):
        self.texts = texts
        self.labels = labels
        self.tokenizer = tokenizer
        self.max_len = max_len

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        encoding = self.tokenizer(
            self.texts[idx],
            truncation=True,
            padding="max_length",
            max_length=self.max_len,
            return_tensors="pt"
        )

        return {
            "input_ids": encoding["input_ids"].squeeze(),
            "attention_mask": encoding["attention_mask"].squeeze(),
            "labels": torch.tensor(self.labels[idx])
        }

train_loader = DataLoader(
    TextDataset(X_train, y_train, tokenizer),
    batch_size=16,
    shuffle=True
)

test_loader = DataLoader(
    TextDataset(X_test, y_test, tokenizer),
    batch_size=16
)

class RobertaClassifier(nn.Module):
    def __init__(self, num_classes):
        super().__init__()
        self.roberta = RobertaModel.from_pretrained("roberta-base")
        self.fc = nn.Linear(768, num_classes)

    def forward(self, input_ids, attention_mask):
        out = self.roberta(input_ids=input_ids, attention_mask=attention_mask)
        cls = out.last_hidden_state[:, 0]
        return self.fc(cls)

class LSTMClassifier(nn.Module):
    def __init__(self, num_classes):
        super().__init__()
        self.roberta = RobertaModel.from_pretrained("roberta-base")
        self.lstm = nn.LSTM(768, 128, batch_first=True)
        self.fc = nn.Linear(128, num_classes)

    def forward(self, input_ids, attention_mask):
        emb = self.roberta(input_ids=input_ids, attention_mask=attention_mask).last_hidden_state
        _, (h, _) = self.lstm(emb)
        return self.fc(h[-1])

class BiLSTMClassifier(nn.Module):
    def __init__(self, num_classes):
        super().__init__()
        self.roberta = RobertaModel.from_pretrained("roberta-base")
        self.bilstm = nn.LSTM(768, 128, batch_first=True, bidirectional=True)
        self.fc = nn.Linear(256, num_classes)

    def forward(self, input_ids, attention_mask):
        emb = self.roberta(input_ids=input_ids, attention_mask=attention_mask).last_hidden_state
        _, (h, _) = self.bilstm(emb)
        h_cat = torch.cat((h[-2], h[-1]), dim=1)
        return self.fc(h_cat)

def train(model, loader, optimizer, criterion, device):
    model.train()
    for batch in loader:
        optimizer.zero_grad()
        input_ids = batch["input_ids"].to(device)
        attention_mask = batch["attention_mask"].to(device)
        labels = batch["labels"].to(device)

        outputs = model(input_ids, attention_mask)
        loss = criterion(outputs, labels)

        loss.backward()
        optimizer.step()

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

models = {
    "roberta": RobertaClassifier(NUM_CLASSES).to(device),
    "lstm": LSTMClassifier(NUM_CLASSES).to(device),
    "bilstm": BiLSTMClassifier(NUM_CLASSES).to(device)
}

criterion = nn.CrossEntropyLoss()

for name, model in models.items():
    optimizer = torch.optim.AdamW(model.parameters(), lr=2e-5)
    for epoch in range(2):
        train(model, train_loader, optimizer, criterion, device)

def soft_voting(models, loader, device):
    probs = []
    true_labels = []

    for model in models.values():
        model.eval()

    with torch.no_grad():
        for batch in loader:
            input_ids = batch["input_ids"].to(device)
            attention_mask = batch["attention_mask"].to(device)

            model_probs = []

            for model in models.values():
                logits = model(input_ids, attention_mask)
                model_probs.append(torch.softmax(logits, dim=1))

            avg_prob = torch.mean(torch.stack(model_probs), dim=0)
            probs.append(avg_prob.cpu())
            true_labels.append(batch["labels"])

    probs = torch.cat(probs)
    true_labels = torch.cat(true_labels)

    preds = torch.argmax(probs, dim=1)
    return true_labels.numpy(), preds.numpy()

y_true, y_pred = soft_voting(models, test_loader, device)

print(classification_report(
    y_true, y_pred,
    target_names=[str(c) for c in label_encoder.classes_]
))

print("Macro F1:", f1_score(y_true, y_pred, average="macro"))

def predict_sentence_class(sentence, models, tokenizer, label_encoder, device, max_len=128):
    # Tokenize the input sentence
    encoding = tokenizer(
        sentence,
        truncation=True,
        padding="max_length",
        max_length=max_len,
        return_tensors="pt"
    )

    input_ids = encoding["input_ids"].to(device)
    attention_mask = encoding["attention_mask"].to(device)

    # Get predictions from all models and perform soft voting
    model_probs = []
    for model in models.values():
        model.eval()
        with torch.no_grad():
            logits = model(input_ids, attention_mask)
            model_probs.append(torch.softmax(logits, dim=1))

    avg_prob = torch.mean(torch.stack(model_probs), dim=0)
    predicted_class_id = torch.argmax(avg_prob, dim=1).item()

    # Convert class ID back to original label
    predicted_class_label = label_encoder.inverse_transform([predicted_class_id])[0]

    return predicted_class_label

# Example usage:
sentence_to_test = "This is a test sentence about hate speech."
predicted_label = predict_sentence_class(
    sentence_to_test, models, tokenizer, label_encoder, device
)

print(f"The sentence '{sentence_to_test}' belongs to class: {predicted_label}")

sentence_to_test_2 = "You are beautiful and kind."
predicted_label_2 = predict_sentence_class(
    sentence_to_test_2, models, tokenizer, label_encoder, device
)

print(f"The sentence '{sentence_to_test_2}' belongs to class: {predicted_label_2}")

sentence_to_test_3 = "I hate you so much, you are a horrible person!"
predicted_label_3 = predict_sentence_class(
    sentence_to_test_3, models, tokenizer, label_encoder, device
)

print(f"The sentence '{sentence_to_test_3}' belongs to class: {predicted_label_3}")