# -*- coding: utf-8 -*-
"""knowledge distillation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X5iUC9lHrOgpeN7uJbA79dzYgi5xZufN
"""

!pip install transformers datasets scikit-learn torch torchvision torchaudio

!pip install nltk emoji

import re
import string
import emoji
import nltk

nltk.download('punkt')

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report, f1_score

from transformers import RobertaTokenizer, RobertaModel
from torch.optim import AdamW

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

df = pd.read_csv("/content/Twitter_HateSpeech.csv")

def clean_text(text):
    text = str(text).lower()

    # Remove URLs
    text = re.sub(r'http\S+|www\S+', '', text)

    # Remove mentions and hashtags
    text = re.sub(r'@\w+|#\w+', '', text)

    # Remove emojis
    text = emoji.replace_emoji(text, replace='')

    # Remove numbers
    text = re.sub(r'\d+', '', text)

    # Remove punctuation
    text = text.translate(str.maketrans('', '', string.punctuation))

    # Remove extra spaces
    text = re.sub(r'\s+', ' ', text).strip()

    return text

df = pd.read_csv("/content/Twitter_HateSpeech.csv")

df["tweet"] = df["tweet"].apply(clean_text)

# Remove empty rows after cleaning
df = df[df["tweet"].str.len() > 3].reset_index(drop=True)

label_encoder = LabelEncoder()
df["class"] = label_encoder.fit_transform(df["class"])

num_classes = len(label_encoder.classes_)

train_texts, val_texts, train_labels, val_labels = train_test_split(
    df["tweet"].tolist(),
    df["class"].tolist(),
    test_size=0.2,
    random_state=42,
    stratify=df["class"]
)

tokenizer = RobertaTokenizer.from_pretrained("roberta-base")

def tokenize(texts, labels):
    encodings = tokenizer(
        texts,
        padding=True,
        truncation=True,
        max_length=128,
        return_tensors="pt"
    )
    return encodings, torch.tensor(labels)

train_enc, train_y = tokenize(train_texts, train_labels)
val_enc, val_y = tokenize(val_texts, val_labels)

class TextDataset(Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        item = {k: v[idx] for k, v in self.encodings.items()}
        item["labels"] = self.labels[idx]
        return item

    def __len__(self):
        return len(self.labels)

train_dataset = TextDataset(train_enc, train_y)
val_dataset = TextDataset(val_enc, val_y)

train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=16)

class RobertaTeacher(nn.Module):
    def __init__(self, num_classes):
        super().__init__()
        self.roberta = RobertaModel.from_pretrained("roberta-base")
        self.fc = nn.Linear(self.roberta.config.hidden_size, num_classes)

    def forward(self, input_ids, attention_mask):
        out = self.roberta(input_ids=input_ids, attention_mask=attention_mask)
        cls = out.last_hidden_state[:, 0]
        return self.fc(cls)

teacher = RobertaTeacher(num_classes).to(device)
optimizer = AdamW(teacher.parameters(), lr=2e-5)
criterion = nn.CrossEntropyLoss()

def train_teacher(model, loader):
    model.train()
    for batch in loader:
        optimizer.zero_grad()
        input_ids = batch["input_ids"].to(device)
        attention_mask = batch["attention_mask"].to(device)
        labels = batch["labels"].to(device)

        logits = model(input_ids, attention_mask)
        loss = criterion(logits, labels)

        loss.backward()
        optimizer.step()

for epoch in range(3):
    train_teacher(teacher, train_loader)
    print(f"Teacher Epoch {epoch+1} done")

def get_soft_labels(model, loader, temperature=4.0):
    model.eval()
    all_soft = []

    with torch.no_grad():
        for batch in loader:
            input_ids = batch["input_ids"].to(device)
            attention_mask = batch["attention_mask"].to(device)

            logits = model(input_ids, attention_mask)
            soft = F.softmax(logits / temperature, dim=1)
            all_soft.append(soft.cpu())

    return torch.cat(all_soft)

soft_labels = get_soft_labels(teacher, train_loader)

vocab_size = tokenizer.vocab_size
embedding_dim = 300

embedding = nn.Embedding(vocab_size, embedding_dim)

class LSTMStudent(nn.Module):
    def __init__(self):
        super().__init__()
        self.embedding = embedding
        self.lstm = nn.LSTM(embedding_dim, 128, batch_first=True)
        self.fc = nn.Linear(128, num_classes)

    def forward(self, x):
        emb = self.embedding(x)
        _, (h, _) = self.lstm(emb)
        return self.fc(h[-1])

class BiLSTMStudent(nn.Module):
    def __init__(self):
        super().__init__()
        self.embedding = embedding
        self.lstm = nn.LSTM(embedding_dim, 128, batch_first=True, bidirectional=True)
        self.fc = nn.Linear(256, num_classes)

    def forward(self, x):
        emb = self.embedding(x)
        _, (h, _) = self.lstm(emb)
        h = torch.cat((h[-2], h[-1]), dim=1)
        return self.fc(h)

class CNNStudent(nn.Module):
    def __init__(self):
        super().__init__()
        self.embedding = embedding
        self.conv = nn.Conv1d(embedding_dim, 128, kernel_size=5)
        self.pool = nn.AdaptiveMaxPool1d(1)
        self.fc = nn.Linear(128, num_classes)

    def forward(self, x):
        emb = self.embedding(x).permute(0, 2, 1)
        conv = F.relu(self.conv(emb))
        pooled = self.pool(conv).squeeze(-1)
        return self.fc(pooled)

def distillation_loss(student_logits, true_labels, teacher_soft, alpha=0.5, T=4.0):
    hard_loss = F.cross_entropy(student_logits, true_labels)
    soft_loss = F.kl_div(
        F.log_softmax(student_logits / T, dim=1),
        teacher_soft,
        reduction="batchmean"
    )
    return alpha * hard_loss + (1 - alpha) * soft_loss

def train_student(model, loader, soft_labels):
    model.train()
    optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)
    idx = 0

    for batch in loader:
        optimizer.zero_grad()
        input_ids = batch["input_ids"].to(device)
        labels = batch["labels"].to(device)

        logits = model(input_ids)
        loss = distillation_loss(
            logits,
            labels,
            soft_labels[idx: idx + len(labels)].to(device)
        )

        loss.backward()
        optimizer.step()
        idx += len(labels)

student = BiLSTMStudent().to(device)   # change to LSTMStudent / CNNStudent

for epoch in range(5):
    train_student(student, train_loader, soft_labels)
    print(f"Student Epoch {epoch+1} done")

student = LSTMStudent().to(device)   # change to LSTMStudent / CNNStudent

for epoch in range(5):
    train_student(student, train_loader, soft_labels)
    print(f"Student Epoch {epoch+1} done")

def evaluate(model, loader):
    model.eval()
    preds, labels = [], []

    with torch.no_grad():
        for batch in loader:
            logits = model(batch["input_ids"].to(device))
            preds.extend(torch.argmax(logits, 1).cpu().numpy())
            labels.extend(batch["labels"].numpy())

    print(classification_report(labels, preds, target_names=label_encoder.classes_.astype(str)))

evaluate(student, val_loader)

def predict_sentence_class(sentence, model, tokenizer, label_encoder, device):
    model.eval()
    # Tokenize the input sentence
    encoding = tokenizer(
        sentence,
        padding=True,
        truncation=True,
        max_length=128,
        return_tensors="pt"
    )

    input_ids = encoding["input_ids"].to(device)

    # For LSTM/CNN student models, we only need input_ids
    # For RobertaTeacher, we would also need attention_mask

    with torch.no_grad():
        logits = model(input_ids)
        probabilities = F.softmax(logits, dim=1)
        predicted_class_idx = torch.argmax(probabilities, dim=1).item()

    # Decode the class index back to the original label
    predicted_label = label_encoder.inverse_transform([predicted_class_idx])[0]
    return predicted_label

# Example usage:
user_sentence = "This is a test sentence."
predicted_class = predict_sentence_class(
    user_sentence,
    student, # Using the last trained student model (LSTMStudent in this case)
    tokenizer,
    label_encoder,
    device
)

print(f"The sentence: '{user_sentence}' is classified as: {predicted_class}")

user_sentence_2 = "You are a really nice person!"
predicted_class_2 = predict_sentence_class(
    user_sentence_2,
    student,
    tokenizer,
    label_encoder,
    device
)
print(f"The sentence: '{user_sentence_2}' is classified as: {predicted_class_2}")

user_sentence_3 = "This is a very bad word to say."
predicted_class_3 = predict_sentence_class(
    user_sentence_3,
    student,
    tokenizer,
    label_encoder,
    device
)
print(f"The sentence: '{user_sentence_3}' is classified as: {predicted_class_3}")

