# -*- coding: utf-8 -*-
"""Morphed_lstm_gru_cnn

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BGIhknFcNygaJ6_kdaPQg5YktkCKLUuc
"""

import os
import zipfile
import cv2
import numpy as np
import pandas as pd
from PIL import Image
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score, f1_score
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import ReduceLROnPlateau, EarlyStopping
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import warnings
warnings.filterwarnings('ignore')

print("✅ All required libraries imported successfully!")

# Dataset preparation with multiple options
def download_and_preprocess_dataset():
    """Download and preprocess CASIA dataset"""
    print("📥 Setting up dataset download...")

    # Option 1: Use uploaded zip file
    print("🔐 Please upload your CASIA dataset zip file...")
    from google.colab import files

    try:
        uploaded = files.upload()

        # Find uploaded zip file
        zip_files = [f for f in uploaded.keys() if f.endswith('.zip')]
        if not zip_files:
            print("❌ No zip file found in upload.")
            return None

        zip_path = f"/content/{zip_files[0]}"
        extract_path = "/content/dataset"

        print(f"📂 Extracting {zip_files[0]}...")
        with zipfile.ZipFile(zip_path, 'r') as zip_ref:
            zip_ref.extractall(extract_path)

        print("✅ Dataset extracted successfully!")

        # Show extracted structure
        print("\n📁 Extracted dataset structure:")
        !find /content/dataset -type d | head -20
        print("\n📄 Sample image files:")
        !find /content/dataset -name "*.jpg" -o -name "*.jpeg" -o -name "*.png" -o -name "*.tif" | head -10

        return extract_path

    except Exception as e:
        print(f"❌ Upload failed: {e}")
        return None

def mount_google_drive():
    """Mount Google Drive and check for dataset"""
    try:
        from google.colab import drive
        drive.mount('/content/drive')

        drive_path = "/content/drive/MyDrive/casia_dataset"
        if os.path.exists(drive_path):
            print(f"✅ Found dataset in Google Drive: {drive_path}")
            # Copy to Colab
            !cp -r "{drive_path}" /content/dataset
            print("✅ Dataset copied to Colab environment")
            return "/content/dataset"
        else:
            print("❌ Dataset not found in Google Drive")
            print("📥 Please upload CASIA dataset to:")
            print(f"   {drive_path}")
            print("Then re-run this cell")
            return None
    except Exception as e:
        print(f"❌ Google Drive mount failed: {e}")
        return None

def download_preprocessed_dataset():
    """Download preprocessed dataset from cloud storage"""
    try:
        print("📥 Downloading preprocessed CASIA dataset...")

        # From GitHub (example - you need actual URL)
        url = "https://github.com/datasets/image-forensics/raw/main/casia_sample.zip"

        import requests
        print(f"Downloading from: {url}")
        response = requests.get(url, stream=True)

        zip_path = "/content/casia_preprocessed.zip"
        with open(zip_path, 'wb') as f:
            for chunk in response.iter_content(chunk_size=8192):
                f.write(chunk)

        extract_path = "/content/dataset"
        with zipfile.ZipFile(zip_path, 'r') as zip_ref:
            zip_ref.extractall(extract_path)

        print("✅ Preprocessed dataset downloaded!")
        return extract_path

    except Exception as e:
        print(f"❌ Preprocessed download failed: {e}")
        return None

def create_sample_casia_dataset():
    """Create a sample CASIA-like dataset for testing"""
    print("🔄 Creating sample CASIA-like dataset for demonstration...")

    sample_path = "/content/casia_sample"
    os.makedirs(sample_path, exist_ok=True)

    # Create CASIA-like directory structure
    authentic_path = os.path.join(sample_path, "Au")
    tampered_path = os.path.join(sample_path, "Tp")
    os.makedirs(authentic_path, exist_ok=True)
    os.makedirs(tampered_path, exist_ok=True)

    # Create realistic sample images
    print("🎨 Generating realistic tampered and authentic images...")

    for i in range(200):  # More images for better training
        # Authentic images (natural)
        authentic_img = np.random.randint(150, 220, (256, 256, 3), dtype=np.uint8)
        # Add realistic texture
        noise = np.random.normal(0, 15, (256, 256, 3)).astype(np.int16)
        authentic_img = np.clip(authentic_img + noise, 0, 255).astype(np.uint8)
        # Add some natural patterns
        for _ in range(np.random.randint(3, 8)):
            x, y = np.random.randint(0, 200, 2)
            w, h = np.random.randint(10, 40, 2)
            color = np.random.randint(180, 230, 3)
            cv2.rectangle(authentic_img, (x, y), (x+w, y+h), color.tolist(), -1)

        cv2.imwrite(os.path.join(authentic_path, f"Au_{i:05d}.jpg"), authentic_img)

        # Tampered images (with visible artifacts)
        tampered_img = np.random.randint(100, 180, (256, 256, 3), dtype=np.uint8)
        # Add tampering artifacts
        # 1. Copy-move artifact
        src_x, src_y = np.random.randint(30, 100, 2)
        dst_x, dst_y = np.random.randint(150, 200, 2)
        patch_size = np.random.randint(20, 50)
        patch = tampered_img[src_y:src_y+patch_size, src_x:src_x+patch_size].copy()
        tampered_img[dst_y:dst_y+patch_size, dst_x:dst_x+patch_size] = patch

        # 2. Edge inconsistencies
        cv2.rectangle(tampered_img, (dst_x-1, dst_y-1),
                     (dst_x+patch_size+1, dst_y+patch_size+1),
                     (0, 0, 255), 1)

        # 3. Color mismatch
        if np.random.random() > 0.5:
            color_shift = np.random.randint(-30, 30, 3)
            tampered_img[dst_y:dst_y+patch_size, dst_x:dst_x+patch_size] = \
                np.clip(tampered_img[dst_y:dst_y+patch_size, dst_x:dst_x+patch_size] + color_shift, 0, 255)

        cv2.imwrite(os.path.join(tampered_path, f"Tp_{i:05d}.jpg"), tampered_img)

        if (i + 1) % 50 == 0:
            print(f"✅ Generated {i + 1} images...")

    print(f"✅ Created sample CASIA-like dataset with 200 authentic and 200 tampered images")
    print(f"📁 Sample structure:")
    print(f"   {sample_path}/")
    print(f"   ├── Au/ (Authentic images)")
    print(f"   └── Tp/ (Tampered images)")

    return sample_path

# Image preprocessing parameters
IMG_SIZE = (224, 224)
BATCH_SIZE = 32
EPOCHS = 15

# COMPREHENSIVE PREPROCESSING
class AdvancedImagePreprocessor:
    """Advanced image preprocessing for image forensics"""

    def __init__(self, img_size=IMG_SIZE):
        self.img_size = img_size

    def apply_advanced_preprocessing(self, image):
        """Apply comprehensive preprocessing pipeline"""
        if image is None:
            return None

        processed_image = image.copy()

        # STEP 1: Ensure image has 3 channels
        if len(processed_image.shape) == 2:
            processed_image = cv2.cvtColor(processed_image, cv2.COLOR_GRAY2BGR)

        # STEP 2: Color Space Conversion
        processed_image = cv2.cvtColor(processed_image, cv2.COLOR_BGR2RGB)

        # STEP 3: Noise Reduction (adaptive)
        if processed_image.shape[0] > 100 and processed_image.shape[1] > 100:
            processed_image = cv2.GaussianBlur(processed_image, (3, 3), 0)

        # STEP 4: Histogram Equalization (CLAHE) for better contrast
        lab = cv2.cvtColor(processed_image, cv2.COLOR_RGB2LAB)
        lab_planes = list(cv2.split(lab))
        clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8, 8))
        lab_planes[0] = clahe.apply(lab_planes[0])
        lab = cv2.merge(lab_planes)
        processed_image = cv2.cvtColor(lab, cv2.COLOR_LAB2RGB)

        # STEP 5: Edge preservation (optional, can help with tampering detection)
        processed_image = cv2.bilateralFilter(processed_image, 9, 75, 75)

        # STEP 6: Resize to target size
        processed_image = cv2.resize(processed_image, self.img_size)

        # STEP 7: Normalize pixel values to [0,1]
        processed_image = processed_image.astype('float32') / 255.0

        return processed_image

def load_casia_dataset(base_path, max_images=2000):
    """Load CASIA dataset with proper structure understanding"""
    images = []
    labels = []

    if base_path is None or not os.path.exists(base_path):
        print(f"❌ Invalid base path: {base_path}")
        return images, labels

    print(f"🔍 Loading dataset from: {base_path}")

    preprocessor = AdvancedImagePreprocessor()
    valid_extensions = ('.jpg', '.jpeg', '.png', '.bmp', '.tiff', '.tif', '.gif')

    image_count = 0

    # Check for standard CASIA structure
    au_path = os.path.join(base_path, "Au")
    tp_path = os.path.join(base_path, "Tp")

    if os.path.exists(au_path) and os.path.exists(tp_path):
        print("✅ Found standard CASIA structure (Au/Tp folders)")

        # Load authentic images
        print("📥 Loading authentic images...")
        au_files = [f for f in os.listdir(au_path) if f.lower().endswith(valid_extensions)]
        print(f"Found {len(au_files)} authentic images")

        for file in au_files[:min(len(au_files), max_images//2)]:
            file_path = os.path.join(au_path, file)
            try:
                img = cv2.imread(file_path)
                if img is not None:
                    processed_img = preprocessor.apply_advanced_preprocessing(img)
                    if processed_img is not None:
                        images.append(processed_img)
                        labels.append(0)  # Authentic
                        image_count += 1

                        if image_count % 100 == 0:
                            print(f"✅ Loaded {image_count} images...")
            except Exception as e:
                continue

        # Load tampered images
        print("📥 Loading tampered images...")
        tp_files = [f for f in os.listdir(tp_path) if f.lower().endswith(valid_extensions)]
        print(f"Found {len(tp_files)} tampered images")

        for file in tp_files[:min(len(tp_files), max_images//2)]:
            file_path = os.path.join(tp_path, file)
            try:
                img = cv2.imread(file_path)
                if img is not None:
                    processed_img = preprocessor.apply_advanced_preprocessing(img)
                    if processed_img is not None:
                        images.append(processed_img)
                        labels.append(1)  # Tampered
                        image_count += 1

                        if image_count % 100 == 0:
                            print(f"✅ Loaded {image_count} images...")
            except Exception as e:
                continue
    else:
        # Alternative structure detection
        print("⚠️ Using alternative structure detection...")
        for root, dirs, files in os.walk(base_path):
            for file in files:
                if image_count >= max_images:
                    break

                if file.lower().endswith(valid_extensions):
                    file_path = os.path.join(root, file)

                    try:
                        img = cv2.imread(file_path)
                        if img is not None:
                            processed_img = preprocessor.apply_advanced_preprocessing(img)

                            if processed_img is not None:
                                # Determine label
                                file_lower = file.lower()
                                path_lower = root.lower()

                                # CASIA naming patterns
                                if 'au' in file_lower or 'au_' in file_lower or 'authentic' in path_lower:
                                    label = 0
                                elif 'tp' in file_lower or 'tp_' in file_lower or 'tamp' in path_lower or 'splice' in path_lower:
                                    label = 1
                                else:
                                    # Skip if unsure
                                    continue

                                images.append(processed_img)
                                labels.append(label)
                                image_count += 1

                                if image_count % 100 == 0:
                                    print(f"✅ Loaded {image_count} images...")

                    except Exception as e:
                        continue

    print(f"🎯 Total images loaded: {len(images)}")
    if len(images) > 0:
        authentic_count = np.sum(np.array(labels) == 0)
        tampered_count = np.sum(np.array(labels) == 1)
        print(f"📊 Authentic: {authentic_count}, Tampered: {tampered_count}")
        print(f"📊 Class balance: {authentic_count/(authentic_count+tampered_count):.2%} authentic")

    return images, labels

# MODEL DEFINITIONS
def create_enhanced_cnn_model(input_shape=(224, 224, 3)):
    """Enhanced CNN model for image forensics"""
    model = keras.Sequential([
        layers.Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=input_shape),
        layers.BatchNormalization(),
        layers.Conv2D(32, (3, 3), activation='relu', padding='same'),
        layers.MaxPooling2D(2, 2),
        layers.Dropout(0.2),

        layers.Conv2D(64, (3, 3), activation='relu', padding='same'),
        layers.BatchNormalization(),
        layers.Conv2D(64, (3, 3), activation='relu', padding='same'),
        layers.MaxPooling2D(2, 2),
        layers.Dropout(0.3),

        layers.Conv2D(128, (3, 3), activation='relu', padding='same'),
        layers.BatchNormalization(),
        layers.Conv2D(128, (3, 3), activation='relu', padding='same'),
        layers.MaxPooling2D(2, 2),
        layers.Dropout(0.4),

        layers.Conv2D(256, (3, 3), activation='relu', padding='same'),
        layers.BatchNormalization(),
        layers.GlobalAveragePooling2D(),

        layers.Dense(512, activation='relu', kernel_regularizer=keras.regularizers.l2(0.001)),
        layers.BatchNormalization(),
        layers.Dropout(0.5),
        layers.Dense(256, activation='relu', kernel_regularizer=keras.regularizers.l2(0.001)),
        layers.Dropout(0.3),
        layers.Dense(1, activation='sigmoid')
    ])

    return model

def create_lstm_model(input_shape=(4, 56, 56, 3)):
    """LSTM model for sequential analysis"""
    model = keras.Sequential([
        layers.TimeDistributed(layers.Conv2D(32, (3, 3), activation='relu', padding='same'), input_shape=input_shape),
        layers.TimeDistributed(layers.BatchNormalization()),
        layers.TimeDistributed(layers.MaxPooling2D(2, 2)),
        layers.TimeDistributed(layers.Dropout(0.2)),

        layers.TimeDistributed(layers.Conv2D(64, (3, 3), activation='relu', padding='same')),
        layers.TimeDistributed(layers.BatchNormalization()),
        layers.TimeDistributed(layers.MaxPooling2D(2, 2)),
        layers.TimeDistributed(layers.Flatten()),

        layers.LSTM(128, return_sequences=True, dropout=0.3, recurrent_dropout=0.3),
        layers.LSTM(64, dropout=0.3, recurrent_dropout=0.3),

        layers.Dense(64, activation='relu', kernel_regularizer=keras.regularizers.l2(0.001)),
        layers.Dropout(0.4),
        layers.Dense(32, activation='relu', kernel_regularizer=keras.regularizers.l2(0.001)),
        layers.Dropout(0.3),
        layers.Dense(1, activation='sigmoid')
    ])
    return model

def create_gru_model(input_shape=(4, 56, 56, 3)):
    """GRU model for efficient sequential analysis"""
    model = keras.Sequential([
        layers.TimeDistributed(layers.Conv2D(32, (3, 3), activation='relu', padding='same'), input_shape=input_shape),
        layers.TimeDistributed(layers.BatchNormalization()),
        layers.TimeDistributed(layers.MaxPooling2D(2, 2)),
        layers.TimeDistributed(layers.Dropout(0.2)),

        layers.TimeDistributed(layers.Conv2D(64, (3, 3), activation='relu', padding='same')),
        layers.TimeDistributed(layers.BatchNormalization()),
        layers.TimeDistributed(layers.MaxPooling2D(2, 2)),
        layers.TimeDistributed(layers.Flatten()),

        layers.GRU(128, return_sequences=True, dropout=0.3, recurrent_dropout=0.3),
        layers.GRU(64, dropout=0.3, recurrent_dropout=0.3),

        layers.Dense(64, activation='relu', kernel_regularizer=keras.regularizers.l2(0.001)),
        layers.Dropout(0.4),
        layers.Dense(32, activation='relu', kernel_regularizer=keras.regularizers.l2(0.001)),
        layers.Dropout(0.3),
        layers.Dense(1, activation='sigmoid')
    ])
    return model

def prepare_sequential_data(X_data, seq_length=4):
    """Convert image data to sequential format"""
    if len(X_data) == 0:
        return np.array([])

    X_seq = []
    for img in X_data:
        patches = []
        h, w = img.shape[0], img.shape[1]
        patch_size = h // seq_length

        for i in range(seq_length):
            start_i = i * patch_size
            end_i = min((i + 1) * patch_size, h)
            # Take horizontal slice
            patch = img[start_i:end_i, :56]
            # Resize to fixed size
            patch_resized = cv2.resize(patch, (56, 56))
            patches.append(patch_resized)

        X_seq.append(np.array(patches))

    return np.array(X_seq)

def evaluate_model_comprehensive(model, X_test, y_test, model_name, is_sequential=False):
    """Comprehensive model evaluation with detailed metrics"""
    print(f"\n{'='*50}")
    print(f"EVALUATING {model_name}")
    print(f"{'='*50}")

    if len(X_test) == 0:
        print("❌ No test data available")
        return {'accuracy': 0, 'precision': 0, 'recall': 0, 'f1': 0, 'roc_auc': 0}

    try:
        if is_sequential:
            X_test_processed = prepare_sequential_data(X_test)
        else:
            X_test_processed = X_test

        # Ensure we have valid data
        if len(X_test_processed) == 0:
            print("❌ No valid test data after processing")
            return {'accuracy': 0, 'precision': 0, 'recall': 0, 'f1': 0, 'roc_auc': 0}

        # Predictions
        y_pred_proba = model.predict(X_test_processed, verbose=0)
        y_pred = (y_pred_proba > 0.5).astype(int).flatten()

        # Handle single class case
        if len(np.unique(y_test)) < 2:
            print("⚠️ Only one class present in test data")
            accuracy = accuracy_score(y_test, y_pred)
            print(f"📊 Accuracy: {accuracy:.4f}")
            return {'accuracy': accuracy, 'precision': 0, 'recall': 0, 'f1': 0, 'roc_auc': 0.5}

        # Calculate metrics
        accuracy = accuracy_score(y_test, y_pred)
        precision = precision_score(y_test, y_pred, zero_division=0)
        recall = recall_score(y_test, y_pred, zero_division=0)
        f1 = f1_score(y_test, y_pred, zero_division=0)

        # ROC AUC (handle edge cases)
        try:
            if len(np.unique(y_pred_proba)) > 1:
                roc_auc = roc_auc_score(y_test, y_pred_proba)
            else:
                roc_auc = 0.5
        except:
            roc_auc = 0.5  # Default for edge cases

        print(f"📊 Accuracy: {accuracy:.4f}")
        print(f"📊 Precision: {precision:.4f}")
        print(f"📊 Recall: {recall:.4f}")
        print(f"📊 F1-Score: {f1:.4f}")
        print(f"📊 ROC-AUC: {roc_auc:.4f}")

        # Detailed classification report
        print(f"\n📋 Detailed Classification Report:")
        print(classification_report(y_test, y_pred, target_names=['Authentic', 'Tampered']))

        # Confusion Matrix
        cm = confusion_matrix(y_test, y_pred)

        plt.figure(figsize=(8, 6))
        sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                   xticklabels=['Authentic', 'Tampered'],
                   yticklabels=['Authentic', 'Tampered'])
        plt.title(f'{model_name} - Confusion Matrix')
        plt.ylabel('True Label')
        plt.xlabel('Predicted Label')
        plt.show()

        # ROC Curve
        if len(np.unique(y_pred_proba)) > 1:
            fpr, tpr, _ = roc_curve(y_test, y_pred_proba)

            plt.figure(figsize=(8, 6))
            plt.plot(fpr, tpr, color='darkorange', lw=2, label=f'ROC curve (area = {roc_auc:.2f})')
            plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
            plt.xlim([0.0, 1.0])
            plt.ylim([0.0, 1.05])
            plt.xlabel('False Positive Rate')
            plt.ylabel('True Positive Rate')
            plt.title(f'{model_name} - ROC Curve')
            plt.legend(loc="lower right")
            plt.grid(True, alpha=0.3)
            plt.show()
        else:
            print("⚠️ Cannot plot ROC curve (single probability value)")

        return {
            'accuracy': accuracy,
            'precision': precision,
            'recall': recall,
            'f1': f1,
            'roc_auc': roc_auc
        }

    except Exception as e:
        print(f"❌ Error evaluating {model_name}: {e}")
        import traceback
        traceback.print_exc()
        return {'accuracy': 0, 'precision': 0, 'recall': 0, 'f1': 0, 'roc_auc': 0}

def predict_with_all_models(image_path, cnn_model, lstm_model, gru_model):
    """Predict using all three models"""
    try:
        # Load and preprocess image
        img = cv2.imread(image_path)
        if img is None:
            print(f"❌ Cannot read image: {image_path}")
            return None, None

        preprocessor = AdvancedImagePreprocessor()
        processed_img = preprocessor.apply_advanced_preprocessing(img)

        if processed_img is None:
            print("❌ Failed to preprocess image")
            return None, None

        # CNN prediction
        img_input = np.expand_dims(processed_img, axis=0)
        cnn_pred = cnn_model.predict(img_input, verbose=0)[0][0]

        # LSTM prediction
        img_seq = prepare_sequential_data(np.array([processed_img]))
        if len(img_seq) > 0:
            lstm_pred = lstm_model.predict(img_seq, verbose=0)[0][0]
        else:
            lstm_pred = 0.5  # Default if sequential conversion fails

        # GRU prediction
        if len(img_seq) > 0:
            gru_pred = gru_model.predict(img_seq, verbose=0)[0][0]
        else:
            gru_pred = 0.5  # Default if sequential conversion fails

        predictions = {
            'Enhanced CNN': cnn_pred,
            'LSTM': lstm_pred,
            'GRU': gru_pred
        }

        return predictions, processed_img

    except Exception as e:
        print(f"❌ Prediction error: {e}")
        return None, None

# MAIN EXECUTION FLOW
print("🚀 STARTING ADVANCED MORPHED IMAGE DETECTION SYSTEM")
print("=" * 60)

# Step 1: Try multiple dataset sources
print("\n📥 STEP 1: LOADING DATASET")
print("-" * 30)

dataset_path = None
sources = [
    ("Google Drive", mount_google_drive),
    ("Uploaded file", download_and_preprocess_dataset),
    ("Sample dataset", create_sample_casia_dataset)
]

for source_name, source_func in sources:
    print(f"\n🔄 Trying {source_name}...")
    dataset_path = source_func()

    if dataset_path and os.path.exists(dataset_path):
        print(f"✅ Successfully loaded from {source_name}")
        break

if dataset_path is None:
    print("\n❌ All dataset sources failed")
    print("💡 Creating sample dataset for demonstration...")
    dataset_path = create_sample_casia_dataset()

# Step 2: Explore dataset structure
print("\n🔍 STEP 2: EXPLORING DATASET STRUCTURE")
print("-" * 30)

if dataset_path is None or not os.path.exists(dataset_path):
    print("❌ Dataset path doesn't exist")
else:
    print(f"📁 Exploring: {dataset_path}")
    try:
        for root, dirs, files in os.walk(dataset_path):
            level = root.replace(dataset_path, '').count(os.sep)
            indent = ' ' * 2 * level
            print(f'{indent}{os.path.basename(root)}/')
            subindent = ' ' * 2 * (level + 1)

            # Count image files
            image_files = [f for f in files if f.lower().endswith(('.jpg', '.jpeg', '.png', '.bmp', '.tiff', '.tif'))]

            for file in image_files[:3]:  # Show first 3 image files
                print(f'{subindent}{file}')
            if len(image_files) > 3:
                print(f'{subindent}... and {len(image_files) - 3} more images')
            elif len(image_files) == 0:
                print(f'{subindent}No image files')
    except Exception as e:
        print(f"❌ Error exploring dataset: {e}")

# Step 3: Load dataset
print("\n🔄 STEP 3: LOADING IMAGES")
print("-" * 30)

images, labels = load_casia_dataset(dataset_path, max_images=1000)

if len(images) == 0:
    print("❌ No images loaded from dataset")
    print("💡 Using synthetic data for demonstration...")
    # Create synthetic data
    images = []
    labels = []
    for i in range(300):
        # Authentic
        img = np.random.random((224, 224, 3)).astype('float32')
        images.append(img)
        labels.append(0)
        # Tampered
        img = np.random.random((224, 224, 3)).astype('float32')
        img[100:150, 100:150] = [1, 0, 0]  # Add red square for tampering
        images.append(img)
        labels.append(1)
    print("✅ Created synthetic dataset with tampering artifacts")

print(f"📊 Total images: {len(images)}")
if len(images) > 0:
    authentic_count = np.sum(np.array(labels) == 0)
    tampered_count = np.sum(np.array(labels) == 1)
    print(f"📊 Authentic: {authentic_count}, Tampered: {tampered_count}")

# Convert to numpy arrays
images = np.array(images)
labels = np.array(labels)

# Step 4: Split dataset
print("\n📊 STEP 4: DATA SPLITTING")
print("-" * 30)

if len(images) > 1:
    X_train, X_test, y_train, y_test = train_test_split(
        images, labels, test_size=0.2, random_state=42, stratify=labels
    )

    X_train, X_val, y_train, y_val = train_test_split(
        X_train, y_train, test_size=0.2, random_state=42, stratify=y_train
    )
else:
    # If only one image, use it for everything
    X_train, X_val, X_test = images, images, images
    y_train, y_val, y_test = labels, labels, labels

print(f"📈 Training set: {X_train.shape[0]} images")
print(f"📈 Validation set: {X_val.shape[0]} images")
print(f"📈 Test set: {X_test.shape[0]} images")

# Step 5: Prepare sequential data
print("\n🔧 STEP 5: PREPARING SEQUENTIAL DATA")
print("-" * 30)

if len(X_train) > 0:
    X_train_seq = prepare_sequential_data(X_train)
    X_val_seq = prepare_sequential_data(X_val)
    X_test_seq = prepare_sequential_data(X_test)

    if len(X_train_seq) > 0:
        print(f"📊 Sequential data shape: {X_train_seq.shape}")
    else:
        print("⚠️ Sequential data preparation failed")
else:
    print("⚠️ No training data available for sequential preparation")

# Step 6: Train Enhanced CNN
print("\n🧠 STEP 6: TRAINING ENHANCED CNN")
print("-" * 30)

if len(X_train) > 0:
    cnn_model = create_enhanced_cnn_model()
    cnn_model.compile(
        optimizer=Adam(learning_rate=0.001),
        loss='binary_crossentropy',
        metrics=['accuracy', tf.keras.metrics.Precision(), tf.keras.metrics.Recall()]
    )

    print("CNN Model Summary:")
    cnn_model.summary()

    cnn_history = cnn_model.fit(
        X_train, y_train,
        batch_size=BATCH_SIZE,
        epochs=EPOCHS,
        validation_data=(X_val, y_val),
        callbacks=[
            ReduceLROnPlateau(monitor='val_loss', factor=0.2, patience=3, min_lr=1e-6),
            EarlyStopping(monitor='val_accuracy', patience=5, restore_best_weights=True)
        ],
        verbose=1
    )
else:
    print("❌ No training data for CNN")
    cnn_model = None

# Step 7: Train LSTM
print("\n🧠 STEP 7: TRAINING LSTM")
print("-" * 30)

if len(X_train_seq) > 0:
    lstm_model = create_lstm_model()
    lstm_model.compile(
        optimizer=Adam(learning_rate=0.001),
        loss='binary_crossentropy',
        metrics=['accuracy', tf.keras.metrics.Precision(), tf.keras.metrics.Recall()]
    )

    print("LSTM Model Summary:")
    lstm_model.summary()

    lstm_history = lstm_model.fit(
        X_train_seq, y_train,
        batch_size=BATCH_SIZE,
        epochs=EPOCHS,
        validation_data=(X_val_seq, y_val),
        callbacks=[
            ReduceLROnPlateau(monitor='val_loss', factor=0.2, patience=3, min_lr=1e-6),
            EarlyStopping(monitor='val_accuracy', patience=5, restore_best_weights=True)
        ],
        verbose=1
    )
else:
    print("❌ No sequential data for LSTM")
    lstm_model = None

# Step 8: Train GRU
print("\n🔄 STEP 8: TRAINING GRU")
print("-" * 30)

if len(X_train_seq) > 0:
    gru_model = create_gru_model()
    gru_model.compile(
        optimizer=Adam(learning_rate=0.001),
        loss='binary_crossentropy',
        metrics=['accuracy', tf.keras.metrics.Precision(), tf.keras.metrics.Recall()]
    )

    print("GRU Model Summary:")
    gru_model.summary()

    gru_history = gru_model.fit(
        X_train_seq, y_train,
        batch_size=BATCH_SIZE,
        epochs=EPOCHS,
        validation_data=(X_val_seq, y_val),
        callbacks=[
            ReduceLROnPlateau(monitor='val_loss', factor=0.2, patience=3, min_lr=1e-6),
            EarlyStopping(monitor='val_accuracy', patience=5, restore_best_weights=True)
        ],
        verbose=1
    )
else:
    print("❌ No sequential data for GRU")
    gru_model = None

# Step 10: Interactive Prediction
print("\n" + "="*60)
print("STEP 10: IMAGE DETECTION INTERFACE")
print("="*60)
print("🎯 Image Tampering Detection System Ready!")
print("📁 Upload any image to check if it's authentic or tampered")

# Check if models are available
if cnn_model is None and lstm_model is None and gru_model is None:
    print("❌ No trained models available. Please train models first.")
else:
    while True:
        print("\nOptions:")
        print("1. Upload and test an image")
        print("2. Exit")

        choice = input("\nEnter your choice (1 or 2): ").strip()

        if choice == '1':
            print("\n📁 Please upload an image file...")
            from google.colab import files
            uploaded_files = files.upload()

            if uploaded_files:
                image_filename = list(uploaded_files.keys())[0]
                print(f"\n🔍 Analyzing image: {image_filename}")

                predictions, processed_img = predict_with_all_models(
                    image_filename, cnn_model, lstm_model, gru_model
                )

                if predictions:
                    print("\n📊 MODEL PREDICTIONS:")
                    print("-" * 45)

                    for model_name, pred in predictions.items():
                        confidence = pred if pred > 0.5 else 1 - pred
                        result = "TAMPERED" if pred > 0.5 else "AUTHENTIC"
                        color = "🟥" if pred > 0.5 else "🟩"
                        print(f"{color} {model_name:<12}: {result:<10} (confidence: {confidence:.4f})")

                    # Consensus
                    avg_pred = np.mean(list(predictions.values()))
                    consensus = "TAMPERED" if avg_pred > 0.5 else "AUTHENTIC"
                    overall_confidence = avg_pred if avg_pred > 0.5 else 1 - avg_pred
                    agreement = sum(1 for p in predictions.values() if (p > 0.5) == (avg_pred > 0.5))

                    print(f"\n🏆 FINAL VERDICT: {consensus}")
                    print(f"📊 Overall confidence: {overall_confidence:.4f}")
                    print(f"🤝 Model agreement: {agreement}/3 models")

                    # Display results
                    fig, axes = plt.subplots(1, 2, figsize=(15, 6))

                    # Original image
                    original_img = cv2.imread(image_filename)
                    original_img = cv2.cvtColor(original_img, cv2.COLOR_BGR2RGB)
                    axes[0].imshow(original_img)
                    axes[0].set_title('Uploaded Image')
                    axes[0].axis('off')

                    # Model confidence plot
                    models = list(predictions.keys())
                    confidences = [p if p > 0.5 else 1-p for p in predictions.values()]
                    colors = ['red' if p > 0.5 else 'green' for p in predictions.values()]

                    bars = axes[1].bar(models, confidences, color=colors, alpha=0.7, edgecolor='black')
                    axes[1].set_ylim(0, 1)
                    axes[1].set_ylabel('Confidence Score')
                    axes[1].set_title('Model Confidence Scores')
                    axes[1].grid(True, alpha=0.3)

                    # Add values on bars
                    for bar, confidence in zip(bars, confidences):
                        axes[1].text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.01,
                                    f'{confidence:.3f}', ha='center', va='bottom', fontweight='bold')

                    plt.tight_layout()
                    plt.show()

                    # Clean up
                    if os.path.exists(image_filename):
                        os.remove(image_filename)

                else:
                    print("❌ Failed to analyze image")

            else:
                print("❌ No file uploaded")

        elif choice == '2':
            print("👋 Exiting... Thank you for using the Image Tampering Detection System!")
            break

        else:
            print("❌ Invalid choice")

print("\n🎉 Image Tampering Detection System Completed Successfully!")